### ISSUE TITLE
Fails to build with OpenSSL 1.1

### ISSUE THREAD

**Issue by ssm** [varnish/hitch#100]
During a recent rebuild of all Debian packages using OpenSSL with the upcoming 1.1 version, Hitch fails to build.

The hitch build log is published at https://breakpoint.cc/openssl-1.1-rebuild-2016-05-29/Attempted/hitch_1.2.0-1_amd64-20160529-1428

Some discussion about the OpenSSL API changes are at https://wiki.openssl.org/index.php/1.1_API_Changes

**Comment by sesse** [comment]
I added a patch to fix most but not all of these issues. The last one seems to be tricky; it looks like there's simply no way to set s3->flags anymore, and thus it's also not possible (it would seem) to disable renegotiation in SSLv3. (Of course, people shouldn't be using SSLv3 anyhow, but that's a different story.)

However, it looks to me as if this part simply isn't needed anymore; 0.9.8m (released in response to the referenced CVE) includes support for a more secure form of renegotiation, and renegotiation under the old protocol is refused by default unless one sets SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION. So I guess the simple fix is to simply #ifdef this out on the OpenSSL version—newer OpenSSL versions, and certainly not 1.1.0, should not need it
[hitch-openssl-1.1.0-incomplete.diff.txt](https://github.com/varnish/hitch/files/439615/hitch-openssl-1.1.0-incomplete.diff.txt)

**Comment by ingvarha** [comment]
Similar on fedora rawhide: https://kojipkgs.fedoraproject.org//work/tasks/7586/16357586/build.log

**Comment by ssm** [comment]
OpenSSL 1.1 is now the default version in the upcoming Debian stable release.

**Comment by hermunn** [comment]
I finally got the time to do this. Unsurprisingly, @sesse's work was practically a complete fix, and now the code should compile on both old and new OpenSSL versions.

I have not pushed it to the main hitch repository, but to my own branch (53b731b). This is because the work was done on a virtual machine with Debian 8 and OpenSSL master compiled from source. I hope that someone else can test this on a different environment before we make this final and close the ticket.

Comments are welcome.

**Comment by ingvarha** [comment]
Seems to build fine on el6 and el7, that is i386, ppc64, x86_64, aarch64 and ppc64le. I'll test 32bit arm and other oddities later.

http://koji.fedoraproject.org/koji/taskinfo?taskID=16494950
http://koji.fedoraproject.org/koji/taskinfo?taskID=16494937

Ingvar

**Comment by ingvarha** [comment]
More build logs. Builds fine also on s390x and 32bit arm.

http://s390.koji.fedoraproject.org/koji/taskinfo?taskID=2405079
http://arm.koji.fedoraproject.org/koji/taskinfo?taskID=3778169
http://koji.fedoraproject.org/koji/taskinfo?taskID=16498592

**Comment by hermunn** [comment]
I guess this means that I will push the changes to the main repository. Thanks again to everyone who contributed!

**Comment by ssm** [comment]
I've uploaded hitch 1.4.3 patched with ae5ac53 to Debian.  Thanks. :)
