### ISSUE TITLE
Enabling shared session (with external updates enabled) blocks out signal handler in master process

### ISSUE THREAD

**Issue by p-id** [varnish/hitch#108]
On enabling session-cache with 'USE_SHARED_CACHE'
It seems that a separate ev_loop(...) gets triggered
https://github.com/varnish/hitch/blob/master/src/hitch.c#L4363

This stub eventually blocks out the signal handling loop in master process.
https://github.com/varnish/hitch/blob/master/src/hitch.c#L4375

**Comment by daghf** [comment]
Thank you for the issue and for the fix.

Closing this one now.
