### ISSUE TITLE
Please add an option to disable TLSv1.0

### ISSUE THREAD

**Issue by sesse** [varnish/hitch#114]
TLSv1.0 has security issues, and it would be nice to disable it; either by default, or with a configuration issue. (It's a simple bit flag to OpenSSL, so it's all just a matter of plumbing through the configuration syntax.)

**Comment by lkarsten** [comment]
Thanks for opening the issue.

According to https://blog.varonis.com/ssl-and-tls-1-0-no-longer-acceptable-for-pci-compliance/ disabling TLSv1.0 became a requirement for PCI compliance after June 30th 2016.

I think we should have a look at adding this option.

**Comment by vovcacik** [comment]
Can we do the same for TLSv1.1, thank you.

**Comment by lkarsten** [comment]
@daghf wrote up an excellent specification that @hermunn is implementing these days.

Work is ongoing. I expect it to make it into 1.4.1 in a week or two.

@vovcacik Yes, that will be possible.

**Comment by daghf** [comment]
This should now be in place, see https://github.com/varnish/hitch/blob/master/docs/configuration.md#ssltls-protocol-setting

Only TLSv1.1 and TLSv1.2 are now enabled by default. If you want TLSv1.0 or SSLv3 those will have to be specified explicitly in the ``tls-protos`` configuration setting:

<pre>
    tls-protos = SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
</pre>

**Comment by hermunn** [comment]
This was completed with a6edaaf9a31, and the feature is in 1.4.1. Closing.
