### ISSUE TITLE
make session cache on/off a runtime configurable item

### ISSUE THREAD

**Issue by ingvarha** [varnish/hitch#115]
According to the README of hitch ~1.0, using the session cache might be considered a potential security problem¹. When maintaining a downstream package, I could choose to either compile with or without the session cache enabled (or produce two packages - which I will not do). For now, I use the default, that is without.

Please consider making the session cache a runtime configurable item.

Ingvar

1) From an old mirror at https://libraries.io/github/denisbr/hitch: "However, it's important to acknowledge the inevitable theoretical security tradeoffs associated with the use of this (substantially more complex) binary. Therefore, the deeply paranoid are advised to use only the standard hitch binary at the cost of some performance.",

**Comment by dmatetelki** [comment]
Hi @ingvarha,

Right now, if you configure hitch with `./configure --enable-sessioncache` (which alerts for a dependency:
`configure: error: Must clone https://github.com/haproxy/ebtree to src/ebtree/`)
then session cache become a command line parameters:

```
# hitch -h
...
SOCKET:
...
  -U  --shared-cache-listen=[HOST]:PORT
                              Accept cache updates on UDP (Default: "")
                              NOTE: This option requires enabled SSL session cache.
  -P  --shared-cache-peer=[HOST]:PORT
                              Force iface and ttl to receiv
                              Send cache updates to specified peer
                              NOTE: This option can be specified multiple times.
  -M  --shared-cache-if=IFACE[,TTL]
                              Force iface and ttl to receive and send multicast updates

PERFORMANCE:
...
  -C  --session-cache=NUM    Enable and set SSL session cache to specified number
                             of sessions (Default: 0)
```

Is it not what you would like to have?
