### ISSUE TITLE
Support for ECC Certificates

### ISSUE THREAD

**Issue by Woidla27** [varnish/hitch#116]
Today I tried out hitch for the first time and wondered if ECC certificates are not supported:
`Aug 29 19:40:12 test hitch[8349]: 20160829T194012.643692 [ 8349] {core} hitch 1.1.1 starting`
`Aug 29 19:40:12 test hitch[8349]: 20160829T194012.643884 [ 8349] {core} Loading certificate pem files (1)`
`Aug 29 19:40:12 test hitch[8349]: 20160829T194012.645282 [ 8349] Error loading RSA private key (/etc/ssl/private/test2.pem)`

My PEM file looks like this:
`-----BEGIN EC PARAMETERS-----`
`[...]`
`-----END EC PARAMETERS-----`
`-----BEGIN EC PRIVATE KEY-----`
`[...]`
`-----END EC PRIVATE KEY-----`
`-----BEGIN CERTIFICATE-----`
`[...]`
`-----END CERTIFICATE-----`
`-----BEGIN DH PARAMETERS-----`
`[...]`
`-----END DH PARAMETERS-----`

hitch 1.3.1 | OpenSSL 1.0.2g-fips

**Comment by daghf** [comment]
@Woidla27 could I ask you to try again now?

**Comment by Woidla27** [comment]
@daghf it works fine.

Thank you for the fast update!
