### ISSUE TITLE
RTMPS Not streaming to back end.

### ISSUE THREAD

**Issue by zach-dunton-sf** [varnish/hitch#126]
When streaming to the nginx rtmp module through hitch, the stream connects and then stops immediately. It works when using stunnel as the tls terminator.

config: http://pastebin.com/VSUA365e
logs: http://pastebin.com/7v16K79j

**Comment by lkarsten** [comment]
Importing from pastebin to avoid linkrot.

Log:
```
Sep 27 11:13:11 dev-stream13 hitch: {core} hitch 1.4.1 starting
Sep 27 11:13:11 dev-stream13 hitch: {core} Using OpenSSL version 1000106f.
Sep 27 11:13:11 dev-stream13 hitch[2627]: {core} Listening on 0.0.0.0:1937
Sep 27 11:13:11 dev-stream13 hitch[2627]: {core} Loading certificate pem files (1)
Sep 27 11:13:11 dev-stream13 hitch[2627]: {core} Note: no DH parameters found in /etc/nginx/ssl/aws-dev.domain.full-cert.pem
Sep 27 11:13:11 dev-stream13 hitch[2627]: {core} ECDH Initialized with NIST P-256
Sep 27 11:13:11 dev-stream13 hitch[2627]: {core} No 'ocsp-dir' configured: Automatic retrieval of OCSP staples will be disabled.
Sep 27 11:13:11 dev-stream13 hitch[2627]: {core} hitch 1.4.1 initialization complete
Sep 27 11:13:11 dev-stream13 hitch[2628]: {core} Process 0 online
Sep 27 11:13:11 dev-stream13 hitch[2628]: {core} Successfully attached to CPU #0
Sep 27 11:13:39 dev-stream13 hitch[2628]: 195.226.181.251:49470 :0 8:9 proxy connect
Sep 27 11:13:39 dev-stream13 hitch[2628]: 195.226.181.251:49470 :0 8:9 ssl handshake start
Sep 27 11:13:39 dev-stream13 hitch[2628]: 195.226.181.251:49470 :0 8:9 ssl client handshake revents=1
Sep 27 11:13:39 dev-stream13 hitch[2628]: 195.226.181.251:49470 :0 8:9 ssl client handshake err=SSL_ERROR_WANT_READ
Sep 27 11:13:39 dev-stream13 hitch[2628]: 195.226.181.251:49470 :0 8:9 ssl client handshake revents=1
Sep 27 11:13:39 dev-stream13 hitch[2628]: 195.226.181.251:49470 :0 8:9 ssl client handshake err=SSL_ERROR_WANT_READ
Sep 27 11:13:39 dev-stream13 hitch[2628]: 195.226.181.251:49470 :0 8:9 ssl client handshake revents=1
Sep 27 11:13:39 dev-stream13 hitch[2628]: 195.226.181.251:49470 :0 8:9 ssl end handshake
Sep 27 11:13:39 dev-stream13 hitch[2628]: 195.226.181.251:49470 :56994 8:9 backend connected
Sep 27 11:13:51 dev-stream13 hitch[2628]: 195.226.181.251:49470 :56994 8:9 Connection closed by backend
Sep 27 11:13:51 dev-stream13 hitch[2628]: 195.226.181.251:49470 :56994 8:9 proxy shutdown req=SHUTDOWN_CLEAR
Sep 27 11:13:51 dev-stream13 hitch[2628]: 195.226.181.251:49470 :56994 8:9 proxy shutdown req=SHUTDOWN_HARD
```

Config:
```
frontend = "[*]:1937"
backend = "[127.0.0.1]:1935"
pem-file = "/etc/nginx/ssl/aws-dev.domain.full-cert.pem"
ciphers = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
prefer-server-ciphers = off
ssl-engine = ""
workers = 1
backlog = 100
keepalive = 3600
chroot = "/var/run/hitch"
user = "nobody"
group = ""
quiet = off
syslog = off
syslog-facility = "daemon"
daemon = off
write-ip = off
write-proxy-v1 = off
write-proxy-v2 = off
proxy-proxy = off
sni-nomatch-abort = off
```

**Comment by lkarsten** [comment]
As far as I can tell, up front, from the log, the client connects and then disconnects.

If you run `openssl s_client --connect localhost:1937` and don't type anything until it times out (few seconds), I think you should see an identical log output on the hitch side. Can you give this a try? 

Most likely this is either the client misbehaving, or we speaking SSL/TLS in a way it doesn't expect.

The "proxy connect" log message is somewhat misleading, I think we should change that.

Do you have any debug output from the client side to share?

**Comment by zach-dunton-sf** [comment]
There isn't much useful from the client side.

Client Output: 

> [tls @ 0x7fcbbaf05f00] IO Error: -980607kB time=00:00:02.06 bitrate= 422.8kbits/s speed=2.02x    
av_interleaved_write_frame(): Input/output error
[flv @ 0x7fcbbb03d000] Failed to update header with correct duration.
[flv @ 0x7fcbbb03d000] Failed to update header with correct filesize.
Error writing trailer of rtmps://<hostname>:1937/avin2/d1e73575-793d-43db-9323-eefcd785d6fe?secureToken=DpfcCzCjeSvRXbP_g_jg5Io2SltaJpI4zJ2zB6Ehqsk: Input/output errorframe=   54 fps=4.3 q=32.0 Lsize=     113kB time=00:00:02.16 bitrate= 428.8kbits/s speed=0.173x    
video:106kB audio:192kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[tls @ 0x7fcbbaf05f00] IO Error: -9806

The output from openssl was the same.
> 20160927T120420.667540 [ 2718] 127.0.0.1:57378 :0 8:9 proxy connect
20160927T120420.667557 [ 2718] 127.0.0.1:57378 :0 8:9 ssl handshake start
20160927T120420.667569 [ 2718] 127.0.0.1:57378 :0 8:9 ssl client handshake revents=1
20160927T120420.670587 [ 2718] 127.0.0.1:57378 :0 8:9 ssl client handshake err=SSL_ERROR_WANT_READ
20160927T120420.672206 [ 2718] 127.0.0.1:57378 :0 8:9 ssl client handshake revents=1
20160927T120420.673085 [ 2718] 127.0.0.1:57378 :0 8:9 ssl end handshake
20160927T120420.673225 [ 2718] 127.0.0.1:57378 :47976 8:9 backend connected
20160927T120520.696327 [ 2718] 127.0.0.1:57378 :47976 8:9 Connection closed by backend
20160927T120520.696345 [ 2718] 127.0.0.1:57378 :47976 8:9 proxy shutdown req=SHUTDOWN_CLEAR
20160927T120520.696351 [ 2718] 127.0.0.1:57378 :47976 8:9 proxy shutdown req=SHUTDOWN_HARD

**Comment by lkarsten** [comment]
Thanks for testing. Did you add anything non-standard to the stunnel configuration to make this work? (can you add your stunnel config?)

**Comment by zach-dunton-sf** [comment]
The stunnel config is pretty basic also.
stunnel config:
> debug=7
cert = /etc/nginx/ssl/aws-dev.domain.full-cert.pem
sslVersion = all
chroot = /var/run/stunnel4/
setuid = nobody
setgid = nogroup
pid = /stunnel.pid
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
options = DONT_INSERT_EMPTY_FRAGMENTS
debug = 7
output = /stunnel.log
[rtmps]
accept  = 1936
connect = 1935
TIMEOUTidle = 60

**Comment by lkarsten** [comment]
Thanks. It was the "options = .." part I was curious about. Can you see if proxying through stunnel still works if you comment that out briefly?

**Comment by zach-dunton-sf** [comment]
It still works even with the options line commented out.

**Comment by zach-dunton-sf** [comment]
I think this is actually a problem with ffmpeg and the way it handles tls for rtmp. The fact it seemed to be working with stunnel is an issue with stunnel not closing the connection properly when the remote has a failure.

**Comment by lkarsten** [comment]
Hi. Thanks for the feedback. Good that you figured it out, I was a bit at a loss how to proceed on this.
