### ISSUE TITLE
Question: Documentation regarding configuration file

### ISSUE THREAD

**Issue by wioxjk** [varnish/hitch#128]
Could'nt really find any documentation or examples of a configuration file in /etc/hitch.
Is there any documentation or examples for it?

Thank you

**Comment by lkarsten** [comment]
Hi.

https://github.com/varnish/hitch/blob/master/hitch.conf.example is the example we have currently. General configuration tips are here: https://github.com/varnish/hitch/blob/master/docs/configuration.md
