### ISSUE TITLE
Create hitch.conf(5) man page

### ISSUE THREAD

**Issue by lkarsten** [varnish/hitch#129]
hitch.conf has grown on us, and the example we ship isn't easy to find in a pinch.

The valid configuration file options should be written down in a proper man page.

Ideally we'd sync this up with the internal code generation, but that is a major undertaking and initially I think it is fine to duplicate it.

Suggested pages for inspiration:
man 5 muttrc
man 5 sysctl.conf
man 5 systemd.service

**Comment by Dridi** [comment]
Please see #71, I don't know when I can work on that.

**Comment by hermunn** [comment]
The man page was pushed in 7b0a1fff3c, unfortunately without the introduction of a macro table.
