### ISSUE TITLE
documentation: add a listing of backend servers supporting the PROXY protocol

### ISSUE THREAD

**Issue by bangert** [varnish/hitch#131]
either to the wiki or the documentation

Thanks

**Comment by lkarsten** [comment]
Hi.
Sure, this can fit nicely in the wiki.
We use Hitch with Varnish, but I'm sure such a list would be useful for other cases.

Feel like helping out? :)

**Comment by bangert** [comment]
if varnish is the only known backend implementing the protocol, then a additional sentence like the following would be helpful.

```
The only known backend to implement the PROXY protocol is varnish.
```
https://github.com/varnish/hitch/blob/master/docs/proxy-protocol.md

Thanks

**Comment by lkarsten** [comment]
Hi. What do you mean?
There are many server implementations that can read PROXY, among them haproxy (which invented it) and nginx.

**Comment by bangert** [comment]
ok - i didnt know that, but would have loved to know when i read about hitch and its PROXY protocol. ;-)
the fact that i didnt, disqualifies me from helping any further, i suppose.

**Comment by gquintard** [comment]
Now you know, that qualifies you :-)

**Comment by daghf** [comment]
Hi @bangert 

Willy Tarreau of Haproxy already maintains a list of known PROXY implementations in the PROXY specification. See section 3 in http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt

I think that is a better suited place for this sort of information, and I don't see much value in us duplicating the effort and keeping our own list.

Closing this issue.

**Comment by bangert** [comment]
actually i agree - a link to that section would have been nice though.

maybe my point hasn't been as clear as it could have been. when i first read 
https://github.com/varnish/hitch/blob/master/docs/proxy-protocol.md i did not have any prior knowledge of the PROXY protocol and reading that document led me to believe that it was a hitch invention. the followup question then was why i opened this issue...

the more correct solution is very likely what you link to above (i cant read it currently - haproxy.org appears to be down from where i am).

another solution is of course to assume prior knowledge of the PROXY protocol ;-)

**Comment by daghf** [comment]
Hi

That is a fair point - we certainly don't want to give the impression that PROXY was a Hitch invention. :-)

I've added a link to the PROXY document in the doc page (https://github.com/varnish/hitch/blob/master/docs/proxy-protocol.md), hopefully that should clear things up.

Thanks!
