### ISSUE TITLE
test08-test-configs.sh does not set group on default shipped hitch.conf.example

### ISSUE THREAD

**Issue by ingvarha** [varnish/hitch#132]
When building hitch-1.4.2 on fedora and redhat:

The last test in test08-test-configs.sh runs hitch on the shipped hitch.conf.example. While it uses $GRP for group for all other tests, it does not when ran on hitch.conf.example.

$ tail -4 test08-test-configs.sh

# Test that our example configuration is in fact usable.
hitch --test --config=${TESTDIR}/../../hitch.conf.example ${CERTSDIR}/default.example.com
test "$?" = "0" || die "hitch.conf.example is not valid"

tests$ grep group ../../hitch.conf.example 
group = "nogroup"

as nobody's group on redhat and derivates is "nobody", this fails.

**Comment by lkarsten** [comment]
Thanks Ingvar!
