### ISSUE TITLE
Building 1.4.2 on FreeBSD fails

### ISSUE THREAD

**Issue by michbsd** [varnish/hitch#135]
cc -O2 -g -std=c99 -fno-strict-aliasing -Wall -W -D_GNU_SOURCE  -g -O2   -o hitch configuration.o ringbuffer.o hitch.o cfg_parser.o cfg_lex.o hssl_locks.o asn_gentm.o ocsp.o logging.o foreign/vpf.o foreign/flopen.o foreign/vas.o foreign/vsb.o  -L/usr/local/lib -lssl   -L/usr/local/lib -lcrypto   -L/usr/local/lib -lev   -lrt
gmake[3]: Leaving directory '/usr/ports/security/hitch/work/hitch-hitch-1.4.2/src'
gmake[2]: Leaving directory '/usr/ports/security/hitch/work/hitch-hitch-1.4.2/src'
Making all in src/util
gmake[2]: Entering directory '/usr/ports/security/hitch/work/hitch-hitch-1.4.2/src/util'
depbase=`echo parse_proxy_v2.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
cc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT parse_proxy_v2.o -MD -MP -MF $depbase.Tpo -c -o parse_proxy_v2.o parse_proxy_v2.c &&\
mv -f $depbase.Tpo $depbase.Po
cc  -g -O2   -o parse_proxy_v2 parse_proxy_v2.o
gmake[2]: Leaving directory '/usr/ports/security/hitch/work/hitch-hitch-1.4.2/src/util'
gmake[2]: Entering directory '/usr/ports/security/hitch/work/hitch-hitch-1.4.2'
rst2man --halt=2 ./hitch.man.rst hitch.8
rst2man --halt=2 ./hitch.conf.man.rst hitch.conf.5
echo "# Run 'man hitch.conf' for a description of all options." > hitch.conf.example.tmp
sed -e '1,/^.. example-start/d' \
	-e '/.. example-end/,$d' \
	-e '/^[^ ]/d' hitch.conf.man.rst >> hitch.conf.example.tmp
sed -i -e ':a' -e 'N' -e '$!ba' -e 's/\n\n\n/\n\n/g' -e 's/\n    /\n/g' hitch.conf.example.tmp
sed: 1: ":a": unused label 'a'
sed: -e: No such file or directory
gmake[2]: *** [Makefile:943: hitch.conf.example] Error 1

**Comment by lkarsten** [comment]
Hi. Thanks for reporting. 

@hermunn is working on this right now. I'll assign it to him.

This is of course just the man page build, which can be disabled (commented out) in Makefile.am for hitch itself to build nicely.

**Comment by hermunn** [comment]
I have pushed 2bd44177e76d33d5c to master, and it should fix this. However, I forgot to do a "Fixes: #135" in the commit message. I will close this when we have a verified build on our FreeBSD build servers.

**Comment by michbsd** [comment]
build works now: 

[...]
--- parse_proxy_v2.o ---
depbase=`echo parse_proxy_v2.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DHAVE_CONFIG_H -I. -I../..    -I/usr/local/include  -O2 -pipe  -fstack-protector -fno-strict-aliasing -MT parse_proxy_v2.o -MD -MP -MF $depbase.Tpo -c -o parse_proxy_v2.o parse_proxy_v2.c && mv -f $depbase.Tpo $depbase.Po
--- parse_proxy_v2 ---
cc  -O2 -pipe  -fstack-protector -fno-strict-aliasing  -L/usr/local/lib -fstack-protector -o parse_proxy_v2 parse_proxy_v2.o
--- hitch.conf.example ---
--- hitch.8 ---
--- hitch.conf.5 ---
--- hitch.conf.example ---
echo "# Run 'man hitch.conf' for a description of all options." > hitch.conf.example.tmp
sed -e '1,/^.. example-start/d'  -e '/.. example-end/,$d'  -e '/^[^ ]/d'  -e 's/^    //' hitch.conf.man.rst >> hitch.conf.example.tmp
--- hitch.8 ---
rst2man --halt=2 ./hitch.man.rst hitch.8
--- hitch.conf.5 ---
rst2man --halt=2 ./hitch.conf.man.rst hitch.conf.5
--- hitch.conf.example ---
mv hitch.conf.example.tmp hitch.conf.example
===>  Staging for hitch-1.4.2

Thanks!

**Comment by hermunn** [comment]
Thanks for verifying, @michbsd! Closing this now.
