### ISSUE TITLE
[FreeBSD] build failure in 1.4.3: byacc in src/cfg_parser.y

### ISSUE THREAD

**Issue by zi0r** [varnish/hitch#140]
`===>  Building for hitch-1.4.3
/usr/bin/make  all-recursive
Making all in src
test -f cfg_parser.c || /bin/sh ../build-aux/ylwrap cfg_parser.y y.tab.c cfg_parser.c y.tab.h `echo cfg_parser.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/  -e s/c++$/h++/ -e s/c$/h/` y.output cfg_parser.output -- byacc -d -t 
byacc: e - line 53 of "/wrkdirs/usr/ports/security/hitch/work/hitch-hitch-1.4.3/src/cfg_parser.y", syntax error
%parse-param { hitch_config *cfg }`

**Comment by daghf** [comment]
Hi

Which version of freebsd / byacc is this?

**Comment by zi0r** [comment]
% byacc -V
byacc - 1.9 20141006
% uname -r
10.3-RELEASE-p11

**Comment by daghf** [comment]
Hi

I just tried building this on 10.0-RELEASE-p17 (which is what I had easily available) with byacc and I was not able to reproduce. 

I also looked into the freebsd repos to have a look at the byacc version you are running (https://svnweb.freebsd.org/base/vendor/byacc/20141006/) and from what I can gather this also supports the required `%parse-param` setting.

I know FreeBSD also packages `bison`. Would you mind giving that a spin instead?

**Comment by zi0r** [comment]
Everything is working for me with 1.4.4
