### ISSUE TITLE
Uneven incoming connection distribution to worker processes with SO_REUSEPORT

### ISSUE THREAD

**Issue by ghost** [varnish/hitch#142]
The usage for option SO_REUSEPORT was recently updated in
https://github.com/varnish/hitch/commit/9eb1bc9410043a359afc807ef9a0e57a8691ac59

However, there is an additional issue with using the specific option in the current-code flow which affect high volume traffic sites being serviced by Hitch.

The initial patch in Linux kernel 3.9 for the said option SO_REUSEPORT does explain the intended use to be a case where we can have multiple (unrelated) processes bind to the same IP:PORT pair if and only if the first process chooses to create the first binding with this specific option enabled and the connection would be distributed among the interest processes based on a hash of source/destination ip:port pairs.

The behavior observed in Debian (Jessie/Whezzy) is that it leads to uneven distribution (pretty skewed) of incoming connection to different worker processes, with the initial/first process get '_most_' of the connection (till the RX queue associated with the first core gets full)

**Comment by p-id** [comment]
#https://github.com/varnish/hitch/pull/144

**Comment by p-id** [comment]
Any chance of this particular change also being pushed upstream.

**Comment by p-id** [comment]
Thanks for taking this up.

I can confirm that this does indeed work and help a bit in current stable Debian derivative production environment since past year or so...
