### ISSUE TITLE
ubuntu 14.04 support for "apt-get install hitch"

### ISSUE THREAD

**Issue by shauligal** [varnish/hitch#145]
Currently "apt-get install hitch" works only for Ubuntu 16.04.
Would it be possible to add support for Ubuntu 14.04, which is still very popular?

**Comment by daghf** [comment]
Hi

The packaging is handled by the distributions themselves, so you're probably better off requesting a backport with the Ubuntu guys rather than opening an issue here. I don't know if that is something they would be open to or what the process is.

ping @ssm

**Comment by shauligal** [comment]
Thanks, I've filed a request for back porting:
https://bugs.launchpad.net/ubuntu/+source/hitch/+bug/1650623
