### ISSUE TITLE
TLS Proxy Gate mode

### ISSUE THREAD

**Issue by PascalRD** [varnish/hitch#149]
Can Hitch works as TLS Proxy gate?
For example there are no backend predefined. TLS tunnel builds between hitch and some TLS server from user request.

This does not works 
./hitch --client -f [*]:8080 hitch.pem:

Hitch trys to connect to backend anyway at default value (0:8000).

**Comment by daghf** [comment]
Hi

This is not a bug, and is unlikely to be supported at any point.

Hitch does not support dynamically allocated backends, in fact it only supports a single (static) backend.

Regards,
Dag
