### ISSUE TITLE
proxy shutdown req=SHUTDOWNHARD

### ISSUE THREAD

**Issue by castroflavio** [varnish/hitch#151]
For some reason my connections are being shutdown. Can anybody explain what does proxy shutdown req=SHUTDOWN_HARD mean?

My log looks like this:

ssl client handshake reven
ts=1
20161227T201155.198368 [ 3337] -:46192 :0 7:8 ssl end handshake
20161227T201155.199095 [ 3337] -:46192 :37009 7:8 backend connected
20161227T201157.234875 [ 3337] -:46192 :37009 7:8 Connection closed by backend
20161227T201157.234909 [ 3337] -:46192 :37009 7:8 proxy shutdown req=SHUTDOWN_CLEAR
20161227T201157.234923 [ 3337] -:46192 :37009 7:8 proxy shutdown req=SHUTDOWN_HARD

**Comment by daghf** [comment]
Hi

This means the backend closed the connection. Hitch will follow suit and close the client connection when this happens.

Try checking in the access logs for your backend application to see why it decided to close.

**Comment by castroflavio** [comment]
It turns out this issue was not related to Hitch. The client connected to the frontend lost IP connectivity. For some reason Hitch did not close his side of the connection even not hearing from that client for a while.
