### ISSUE TITLE
100% cpu while running with session cache

### ISSUE THREAD

**Issue by ingvarha** [varnish/hitch#152]
Compiled hitch with ebtree and --enable-sessioncache. Ran

hitch -b [localhost]:80 -n 4 -C 10 default.example.com.pem

hitch used 100% cpu (one core maxed out) in a few seconds.

Another user reported this on hitch-1.3.1 on el6, so this is not a new bug.

Ingvar

[hitch-with-session-cache-eating-100-percent-cpu.txt](https://github.com/varnish/hitch/files/686148/hitch-with-session-cache-eating-100-percent-cpu.txt)

**Comment by p-id** [comment]
It might be due the following line on el6.

https://github.com/varnish/hitch/blob/master/src/hitch.c#L3609

May be it is time to include signal handlers (or at least variable(s) updated by signal handlers via change notification) also as part of ev_loop construct.

**Comment by ingvarha** [comment]
I can reproduce this on fedora25 as well

**Comment by daghf** [comment]
Hi Ingvar,

Thanks for reporting, I was quickly able to reproduce on el6.

Currently looking at it, will get back to you soon.

**Comment by daghf** [comment]
@ingvarha this should be sorted now. Thanks again!

**Comment by ingvarha** [comment]
Great! Test builds for el6 and el7 here: https://copr.fedorainfracloud.org/coprs/ingvar/hitch_with_session_cache/
