### ISSUE TITLE
ECDH public server param reuse

### ISSUE THREAD

**Issue by HLeithner** [varnish/hitch#155]
I don't think that OpenSSL version is the reason at least not OpenSSL 1.0.2j-3.fc24 with Apache Traffic Server 7.0.0-1.fc24 on Fedora has not this Problem.

I'm using OpenSSL 1.0.2j-1~bpo8+1 with hitch 1.4.4 on Debian Jessie and has this Problem.

**Comment by daghf** [comment]
Thanks for reporting.

Seems this should be as simple as setting `SSL_OP_SINGLE_ECDH_USE`. I'll take a look at this tomorrow.

**Comment by daghf** [comment]
This should be fixed now via 5839af05bfc76c2ff4b3cf40072ac637e89dc458
