### ISSUE TITLE
Session resumption (caching)?

### ISSUE THREAD

**Issue by icco** [varnish/hitch#156]
I ran ssllabs on a new hitch install:

https://www.ssllabs.com/ssltest/analyze.html?d=ops.party&s=104.154.142.2

And got the following warning:

![screen shot 2017-01-18 at 21 20 54](https://cloud.githubusercontent.com/assets/20201/22094700/0da00e96-ddc4-11e6-87a3-604c1b915ab2.png)

Is this a configuration thing I need to change with my hitch? Or a bug in hitch? Or other?

Thanks!

**Comment by ismaelpuerto** [comment]
You can use "--enable-sessioncache" to enable (default is off)
