### ISSUE TITLE
listen_all commit breaks multiple frontend sections

### ISSUE THREAD

**Issue by HLeithner** [varnish/hitch#158]
Commit https://github.com/varnish/hitch/commit/db61acf031bee84b09158aa67e06d21d518d43a8 breaks my config in a strange way.

I have multiple frontend sections with diffent IPs and pem files, after testing current master the server presents me wrong (maybe random) certificate.

So db61acf031bee84b09158aa67e06d21d518d43a8 to current master is broken.

**Comment by HLeithner** [comment]
Maybe I should mention that I don't have any wildcard host only explicit IP base frontends.

**Comment by daghf** [comment]
Hi - thanks for reporting.

Are you running current HEAD? There was some breakage introduced in db61acf031bee84b09158aa67e06d21d518d43a8 but that should have been fixed in the subsequent commit.

**Comment by HLeithner** [comment]
At reporting i was on master , after that I searched for the Last working commit and it was the ecdh Reuse commit, I can Check again on monday.

**Comment by HLeithner** [comment]
I tried ef9f40a603fe056b0971896c5c955aea2c24fdfa now and got the same problem I got a certificate for a different IP.

I think I found the Problem.

It seams that if the ```ocsp-dir``` is set hitch answers with random certificates even if hitch disabled ocsp because the directory doesn't exists (That was the case for testing).

After I removed ocsp-dir option hitch works normal again.

**Comment by dmatetelki** [comment]
fixed with #191
