### ISSUE TITLE
Review libev versions for older distros.

### ISSUE THREAD

**Issue by lkarsten** [varnish/hitch#17]
Have a look at the different versions of libev in rhel6/7, debian 7/8 and ubuntu 12.04/14.04. See if there is anything we should know about.

**Comment by aondio** [comment]
There is a bug chapter in this doc attached.
http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#GNU_LINUX_32_BIT_LIMITATIONS

**Comment by lkarsten** [comment]
el6 has 4.03.
el7 has 4.15.

debian jessie has 4.15 (libev4) and 3.9. (libev3)
debian wheezy has 4.11.

ubuntu trusty has 4.15.

changelog: http://cvs.schmorp.de/libev/Changes?view=markup

**Comment by daghf** [comment]
Thanks, Lasse

From briefly looking at the changelog, it seems the few "incompatible changes" listed on there either pre-date the Stud project or otherwise do not apply (we don't use "ev_timer_again").

I'm not concerned - closing this issue.
