### ISSUE TITLE
Centos Package Hitch version 1.4.4 not starting

### ISSUE THREAD

**Issue by hilmarb** [varnish/hitch#170]
Within the centos package the systemd startup script has wrong type "simple" defined, hindering the main process being started. No meaningfull logs will be made of this.

```
[myhost]# tail -3 /var/log/messages
Feb 26 23:54:06 myhost hitch: {core} hitch 1.4.4 starting
Feb 26 23:54:06 myhost hitch[13207]: {core} Loading certificate pem files (1)
Feb 26 23:54:06 myhost hitch[13207]: {core} Daemonized as pid 13208.
```

No process will be seen running however, note the absence of hitch below..

```
[myhost]# ps -ef | grep -i hitch
root     13545 10124  0 00:29 pts/0    00:00:00 grep --color=auto -i hitch
```

Cause:
================================================
wrong type specified in hitch.service

```
[myhost]# diff /usr/lib/systemd/system/hitch.service /tmp/hitch.service.working
21c21
< Type=simple
---
> Type=forking
```

Solution:
================================================
Replace Type=simple with Type=forking in /usr/lib/systemd/system/hitch.service

```
[myhost]# echo "--- /usr/lib/systemd/system/hitch.service2016-12-23 14:33:10.000000000 +0100
> +++ /tmp/hitch.service.backup 2017-02-26 23:59:28.465343937 +0100
> @@ -18,7 +18,7 @@
>  LimitCORE=infinity
>  
>  RuntimeDirectory=hitch
> -Type=simple
> +Type=forking
>  PrivateTmp=true
>  ExecStart=/usr/sbin/hitch --pidfile=/run/hitch/hitch.pid --config=/etc/hitch/hitch.conf
>  ExecReload=/usr/bin/kill -HUP $MAINPID" | patch /usr/lib/systemd/system/hitch.service

[myhost]# systemctl daemon-reload
[myhost]# systemctl start hitch
```

According to systemd documentation:
================================================
Type	Configures the unit process startup type that affects the functionality of ExecStart and related options. One of:

    simple – The default value. The process started with ExecStart is the main process of the service.
    forking – The process started with ExecStart spawns a child process that becomes the main process of the service. The parent process exits when the startup is complete.

**Comment by daghf** [comment]
Hi

I think perhaps the CentOS packaging site is the more appropriate place for this bug, http://rpms.famillecollet.com/rpmphp/zoom.php?rpm=hitch

Maybe you could file a ticket in following the bugzilla link there?

@ingvarha comments?

**Comment by ingvarha** [comment]
The correct place to report a bug agains the fedora/epel version of hitch is in Red Hat's bugzilla, https://bugzilla.redhat.com/

In the fedora and epel package, hitch runs under systemd, do it does not need to daemonize, and starts up in non-forking mode, that is, it does NOT run with --daemon set. This means that **simple** is the correct type.

From the man page hitch(8):

          --daemon
                 Fork into background and become a daemon; this also sets the --quiet option (Default: off)

If hitch runs daemonized as stated in the screendump above, there is either something strange in the users' systemd configuration, or he runs with an old variant from an earlier version of the package, or a non-fedora/epel version.

@hilmarb, what version of the package are you running, and what is its origin?

Also, when patching a systemd unit file, it is reccomended to copy it to /etc/systemd/system and edit it there, to leave the packager's version untouched.

**Comment by denisbr** [comment]
I think this can be closed due to lack of responses. Packaging and systemd-units have also been improved since.
