### ISSUE TITLE
H2 Issues

### ISSUE THREAD

**Issue by faketits** [varnish/hitch#172]
Hi,

We are implementing HItch to terminate SSL  connections, we are having some issues with understanding the h2 implementation logics, if Hitch terminates TLS as it should it shouldn't under any circumstances passthrou h2 as h2 is TLS dependent, but our tcpdump shows that in fact it does passthrou h2 even thou the backend will never except it as it is not encrypted traffic and the h2 RFC clearly demands it to be encrypted (unless it h2c which it isn't), so if anyone could kindly explain what is the use case for h2 with/over hitch and how to implement it correctly, is this battle tested? 

Thanks (and  we love it anyhow :))

**Comment by gquintard** [comment]
Not a bug, please use the mailing list, or come on the varnish IRC channel so we can discuss that.

Very quickly: hitch only care about the SSL/TLS layer and won't look at the H1/H2 layer, it's the L7 layer's responsibility to check this sort of things.
