### ISSUE TITLE
Disabling C99 breaks build with shared-session-cache enabled

### ISSUE THREAD

**Issue by ghost** [varnish/hitch#173]
The following change seems to break building up the current git-master 
https://github.com/varnish/hitch/commit/668c7c064318b51c614654a84f48ac422cd120c0

`configuration.c: In function ‘config_new’:
configuration.c:208:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 0 ; i < MAX_SHCUPD_PEERS; i++)
  ^
configuration.c:208:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
`

**Comment by Dridi** [comment]
As a workaround, does it work if you configure hitch like this?

```
./configure CFLAGS='-g -O2 -std=c99'
```

I don't remember which platform+compiler broke when the flag was present, what's yours?

**Comment by p-id** [comment]
well, the build host is mostly Debian (Jessie) with GCC. Adding flag '-std=c99' does fix this.

`$ gcc -v
--build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10) 
`

**Comment by Dridi** [comment]
Thanks for the details, please use the workaround until a fix lands.
