### ISSUE TITLE
1.4.5 build fails on fedora with "dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]"

### ISSUE THREAD

**Issue by ingvarha** [varnish/hitch#181]
1.4.5 build fails on fedora with

"dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]"

Environment: Fedora 25 on x86_64, gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)

Build log at https://paste.fedoraproject.org/paste/8zWK0hi8sMwc8xB1zbyzW15M1UNdIGYhyRLivL9gydE=

**Comment by ingvarha** [comment]
or here
[build.log.txt](https://github.com/varnish/hitch/files/1044567/build.log.txt)

**Comment by daghf** [comment]
Thanks for spotting this. Could you try adding `-Wno-error=strict-aliasing` to your CFLAGS as a workaround until we fix the code?

**Comment by ingvarha** [comment]
adding -Wno-error=strict-aliasing hides the problem

**Comment by daghf** [comment]
This was due to the libev library's use of casts in its header file that don't quite comply with gcc's understanding of strict aliasing.

I've reverted a previous change and it's back to using `-fno-strict-aliasing` in place of `-Wno-strict-aliasing` now, which fixes the build for epel6/7.
