### ISSUE TITLE
OpenSSL version mismatch after compiling against different version

### ISSUE THREAD

**Issue by Marco208** [varnish/hitch#184]
Hi,

I'm trying to compile hitch against openssl 1.0.2L on CentOS 6. After a successful compile with

```
SSL_LIBS="/usr/local/lib_ssll/lib/libssl.a" CRYPTO_LIBS="/usr/local/lib_ssll/lib/libcrypto.a" LDFLAGS="-ldl" ./configure
make
```
hitch tells me
```
20170612T213347.548749 [23844] WARNING: {core} OpenSSL version mismatch; hitch was compiled with 1000105f, now using 100020cf.
20170612T213347.548793 [23844] {core} Using OpenSSL version 100020cf.
```

Any help would appreciated!

Marco

**Comment by gquintard** [comment]
@Marco208 what was the issue?

**Comment by Marco208** [comment]
@gquintard the following fixed it:

export SSL_CFLAGS="-I/usr/local/lib_ssll/include -L/usr/local/lib_ssll/lib"
export SSL_LIBS=-lssl
export CRYPTO_CFLAGS="-I/usr/local/lib_ssll/include -L/usr/local/lib_ssll/lib"
export CRYPTO_LIBS=-lcrypto
export C_INCLUDE_PATH=/usr/local/lib_ssll/include
export LIBRARY_PATH=/usr/local/lib_ssll/lib

Found a solution by copying this question: https://github.com/varnish/hitch/issues/174
