### ISSUE TITLE
Hitch http/2 problem

### ISSUE THREAD

**Issue by saga1015** [varnish/hitch#186]
I test arch: hitch 1.4.6---->varnish 5.1.2----->nginx 1.13.2 and 
hitch use apln='h2,http/1.1'  and write-proxy-v2=on
varnish 5.1.2 use -a :8080,PROXY and default.vcl  set backend param .proxy_header=1
nginx set listen 81 http2 proxy_protocol.

when I start all test servers ,I use firefox visit https://xxx.xxx.com and use firebug check http header ,I can see X-Firefox-Spdy:h2  ,but no any data be cached by varnish .

please help me ,thank you very very much

**Comment by AxisNL** [comment]
Since varnish does the caching (hitch doesn't do caching) I guess you might want to see the varnish mailing lists for these problems. Provide a minimal working VCL that shows the problem, and a varnishlog there, and you'll probably get a reply back very quickly.
