### ISSUE TITLE
Logging to syslog even when set to syslog = off?

### ISSUE THREAD

**Issue by stbc** [varnish/hitch#187]
Hi everybody,

I got hitch running from the Debian backports repo. Although it states

syslog = off

in the hitch.conf, hitch still logs to syslog:

```
Jul  5 08:03:57 machine hitch[767]: 13x.xxx.xxx.xxx:64751 :0 15:16 Handshake failure: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
Jul  5 08:04:01 machine hitch[766]: 13x.xxx.xxx.xxx::52882 :0 14:15 Handshake failure: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
Jul  5 08:04:01 machine hitch[767]: 13x.xxx.xxx.xxx::51035 :0 15:16 Handshake failure: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
```

Is that a bug? Or it is supposed to be that way....?!

It would be nice to let hitch write those messages (and there are loads) to a separate log file

**Comment by dmatetelki** [comment]
`log_ssl_error` does not honour the logging settings?
I'll take a look.

**Comment by dmatetelki** [comment]
Hi @stbc,

The problem was that hitch turned logging to syslog on at daemonizing.
You can specify a logfile now with `--log-filname=FILE`
