### ISSUE TITLE
hitch with alpn support on centos7?

### ISSUE THREAD

**Issue by AxisNL** [varnish/hitch#189]
At the moment I am running hitch-1.4.5-1.el7.x86_64 on centos7. I see ALPN is not supported, only NPN is. This is because centos 7.3 only supports openssl 1.0.1x, and ALNP support is built into openssl 1.0.2x. Forgive me if I use the wrong terminology, I know a lot about web protocols and caching, but little about building stuff, dependencies, etc.

If I understand correctly I have to wait for centos 7.4 to be released before openssl 1.0.2x is supported, and then I can compile hitch with ALPN support. However, I am very impatient, and I'd like to start playing around with H2 on my staging sites. I've got hundreds of hosts that are managed using puppet and custom scripts, so switching to another OS isn't really an option.

I was thinking: If I compile hitch on a rhel7.4 beta machine, and repackage it with rpmbuild, could I install that rpm on a centos 7.3 machine? Can openssl 1.0.2 be 'baked into' the hitch binary?

**Comment by Dridi** [comment]
You could build (and maintain!) the desired openssl version, and then build hitch against that library.

**Comment by gquintard** [comment]
OBE? https://lists.centos.org/pipermail/centos-announce/2017-September/022532.html

Otherwise, I'd vote wontfix since it's really the distribution job to do this.

**Comment by AxisNL** [comment]
Yup, it works in CentOS 7.4! No fix needed anymore..

**Comment by gquintard** [comment]
Thank you for reporting back!
