### ISSUE TITLE
Listening IP address is ignored in long format frontend config.

### ISSUE THREAD

**Issue by jfp42** [varnish/hitch#194]
This is on Centos 7 running Hitch 1.4.5.

Using this syntax, the ip address is ignored.
frontend = {
    host = "[172.20.1.139]"
    port = "444"
    pem-file =    "/etc/pki/tls/certs/BLAH.crt"
}
20170808T171842.971922 [ 6920] {core} Listening on 0.0.0.0:444
20170808T171842.972026 [ 6920] {core} Listening on [::]:444

Using this syntax, the ip address is used.
frontend="[172.20.1.139]:443"
pem-file =    "/etc/pki/tls/certs/BLAH.crt"

20170808T171436.794115 [ 6847] {core} Listening on 172.20.1.139:443

**Comment by bago** [comment]
This sounds like a MAJOR issue that makes hitch 1.4.5 and 1.4.6 not able to work in a multihomed system as you have no way to bind a specific frontend to an IP: did I get this right?

Shouldn't this deserve an immediate release for 1.4.7 ?

Hitch <= 1.4.4 have memory leaks
Hitch >= 1.4.5 doesn't work with multihoming

Only current viable way is to use a locally patched/built hitch.. not the best thing.

**Comment by Dridi** [comment]
Chiming in, I'd really like to have #209 as part of the next release. Currently waiting for master to incorporate a couple pull request before catching up. I don't know when master will be ready, and neither when the next release is due but I'll make sure not to slow things down in-between.

FYI, the new test framework caught problems in current master that the previous didn't.
