### ISSUE TITLE
hitch-1.4.6 with session cache,  tests failing: test07-nomatch-abort.sh, test13-r82.sh 

### ISSUE THREAD

**Issue by ingvarha** [varnish/hitch#196]
When building hitch-1.4.6 with session cache the test suite fails on tests 07 and 13.

Reproduce: 

tar xvzf hitch-1.4.6.tar.gz
cd hitch-1.4.6/src
git clone https://github.com/haproxy/ebtree.git
cd ebtree
make
cd ../..
./configure --enable-sessioncache
make
make check

Ingvar

**Comment by ingvarha** [comment]
Looks like SNI does not work properly when running with session cache

openssl s_client -servername invalid.example.com -prexit -connect localhost:6514 </dev/null > s_client.ouput.without_session_cache.txt
[s_client.ouput.without_session_cache.txt](https://github.com/varnish/hitch/files/1378676/s_client.ouput.without_session_cache.txt)

140502862665472:error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:ssl/record/rec_layer_s3.c:1399:SSL alert number 112

openssl s_client -servername invalid.example.com -prexit -connect localhost:6514 </dev/null > s_client.ouput.with_session_cache.txt
depth=0 CN = default.example.com
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = default.example.com
verify return:1
DONE
[s_client.ouput.with_session_cache.txt](https://github.com/varnish/hitch/files/1378669/s_client.ouput.with_session_cache.txt)

**Comment by dmatetelki** [comment]
All the tests and the 2 commands work fine for me.

**Comment by ingvarha** [comment]
What platform do you test on? I get this failing on fedora 26 and ubuntu 14.04.

I add the test output logs here. Is there anyway I can add more debug info? 

[test07-nomatch-abort.log.txt](https://github.com/varnish/hitch/files/1395853/test07-nomatch-abort.log.txt)
[test13-r82.log.txt](https://github.com/varnish/hitch/files/1395854/test13-r82.log.txt)

**Comment by ingvarha** [comment]
and the fedora26 logs:

[test07-nomatch-abort.log.txt](https://github.com/varnish/hitch/files/1395871/test07-nomatch-abort.log.txt)
[test13-r82.log.txt](https://github.com/varnish/hitch/files/1395873/test13-r82.log.txt)

**Comment by dmatetelki** [comment]
Hi @ingvarha,
I tested it on ubuntu 16.04.
Thank you for the logs, i'll go though them and i'll get my hands on a fedora vbox image.
