### ISSUE TITLE
accepting proxy protocol

### ISSUE THREAD

**Issue by Exocomp** [varnish/hitch#199]
I know that proxy protocol is supported for sending to backend servers but I don't see it in the doc support for accepting it.  In this scenario Server -> Hitch -> Server since I'm not able to setup Hitch to accept proxy protocol the client ip is dropped (I'm using strictly TCP).  Any suggestions on how I can get around this limitation?  If support is there and I missed it, my apologies please let me know.

Thanks.

**Comment by Dridi** [comment]
I think you are looking for `--proxy-proxy` but according to the manual it only supports v1.

**Comment by Exocomp** [comment]
@Dridi thanks for the quick reply, that worked!

But I could not use both --write-proxy-v2 and --proxy-proxy at the same time, I got the following error:
`Options --write-ip, --write-proxy-proxy, --write-proxy-v1 and --write-proxy-v2 are mutually exclusive.`

However, --proxy-proxy looks to be suitable for my needs.

Thanks again!
