### ISSUE TITLE
hitch proxy protocol dropping connections

### ISSUE THREAD

**Issue by Exocomp** [varnish/hitch#200]
In this scenario Server -> Hitch -> Server, when I enable proxy-proxy, I'm noticing that when I get to 4000 requests/sec at times 10% of the requests are dropped.  

I noticed the same thing using nginx also so it is not related to hitch, closing.

**Comment by Exocomp** [comment]
I did some more testing and I think it is related to proxy protocol v1, any idea when proxy protocol v2 will be supported with hitch for incoming side?

Is there a lot of effort needed for hitch to receive proxy protocol v2, would you be able to provide a high level of where the code base to implement the solution, I might give it a shot and see how far I get.

Thanks,
E

**Comment by Exocomp** [comment]
I implemented proxy protocol v2 per http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt but still saw the same issue, I saw the issue even when using nginx.  So appears that even proxy protocol v2 has the same issue.

I thought openssl might be the issue, I upgraded openssl from "OpenSSL 1.0.2g  1 Mar 2016" to the latest "OpenSSL 1.0.2l 25 May 2017" and still saw the issue.

Using HAProxy in front of hitch I'm see a lot of "Connection resets during transfers" reported by HAProxy so seems there is an issue unless I'm completely missing something.

**Comment by Dridi** [comment]
Thank you for letting us know, however you removed messages regarding the proxy-proxy mode and version 2 of the protocol. We look at new bugs on Mondays, so for us that's later today, please reopen and add the missing comments back if you want us to have a look.

**Comment by Exocomp** [comment]
I left a summary which explains the issue, the other comments weren't relative after all my testing, as I mentioned though the issue is beyond hitch as it happens else where.  I'm working with the HAProxy team who created the Proxy Protocol to see if I can track down what is happening.  I created the post 5 days ago and was wondering if anyone was really interested.
