### ISSUE TITLE
The IP address for backend is assumed to be static.

### ISSUE THREAD

**Issue by rtkbkish** [varnish/hitch#202]
The IP address of our backend changes. We use DNS to map to a set of hosts that can handle incoming connections. The code currently assumes there is single permanent mapping from hostname to IP address.

We need a way to have the code to call getaddrinfo every time a new connection to the backend is opened.

**Comment by dmatetelki** [comment]
duplicate of #84 ?

**Comment by gquintard** [comment]
definitely

**Comment by dmatetelki** [comment]
@rtkbkish : I've started to work on a periodic backend IP check fix, let me update the progress in #84.
