### ISSUE TITLE
Is hitch still under active development?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [varnish/hitch#208]
There seem to be many open feature requests but very few commits in the last 2 years. Is hitch still under active development or should people be looking elsewhere for an SSL / TLS terminator?

**Comment by dmatetelki** [comment]
Hi Ahmed,

Hitch is definitely not dead, it is one of our key products.
We are aware, it just came up in an internal meeting last week that
hitch issues are piling up...

I'm going though them as we speak to start things getting fixed again.

d

**Comment by denisbr** [comment]
The last release of the product was only a couple of months ago. (1.4.6 released on 2017-06-06)
