### ISSUE TITLE
Building without root

### ISSUE THREAD

**Issue by Hixie** [varnish/hitch#211]
I have an environment where I can't install packages as root, but where I'd like to run hitch.

Is there a solution for this?

I can see two possible paths:

### Statically linking hitch into a single binary (which I can build on another system)

Is this a supported configuration? I couldn't figure out how to hold the compilation scripts to make this work.

### Build the libraries locally and point hitch to the local libraries

This seems like it should be supported but I couldn't find any combination of running `./configure` that worked. I tried running `./configure; make` in `/home/ianh/bin/libev/` where I have the [libev](http://dist.schmorp.de/libev/libev-4.24.tar.gz) tarball expanded, followed by running the following in the hitch directory:

```bash
export LIBRARY_PATH='/home/ianh/bin/libev'
export LD_LIBRARY_PATH='/home/ianh/bin/libev'
export LDFLAGS='-L/home/ianh/bin/libev'
./configure
```

...but I get the same message (`configure: error: Cannot find libev.`).

(I noticed that running `./configure; make` in `/home/ianh/bin/libev/` seems to create `libev.la`, not `libev.so`, which may be an issue?)

**Comment by gquintard** [comment]
that will be an issue, you'll need the .so.

Also, why not build varnish on an other machine, and just drag the libs along?

**Comment by Hixie** [comment]
> that will be an issue, you'll need the .so.

Any idea how I get libev to build the .so?

> Also, why not build varnish on an other machine, and just drag the libs along?

I guess I could. That seemed less elegant than just statically linking.

**Comment by gquintard** [comment]
The first question is way out of the scope of this bugtracker. But you are welcome to join us on the varnish-misc mailing-list to discuss it.

For the second one, I don't consider statically linking very elegant. But if that's your gig, I would simply re-run the linking command with different args.

**Comment by Hixie** [comment]
Ok, thanks.
