### ISSUE TITLE
Hitch equivalent to Apache SSLVerifyClient require?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [varnish/hitch#212]
Does Hitch have an equivalent to Apache's SSLVerifyClient require option?

**Comment by lkarsten** [comment]
Background: https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslverifyclient

`This directive sets the Certificate verification level for the Client Authentication. Notice that this directive can be used both in per-server and per-directory context. In per-server context it applies to the client authentication process used in the standard SSL handshake when a connection is established. In per-directory context it forces a SSL renegotiation with the reconfigured client verification level after the HTTP request was read but before the HTTP response is sent.`

As far as I know, there is no client certificate support in Hitch.

**Comment by hjames9** [comment]
Is this on the roadmap to be supported yet?  It would be really useful

**Comment by bago** [comment]
I see in 1.5.0 you added an option to pass some SSL variable using the PROXYv2 protocol: what about adding some more data so to pass the SSL client certificate to the data so we can do the client authentication in the application?

**Comment by lkarsten** [comment]
@bago Is there some software somewhere that does this already? If so, can you supply a link to the implementation?

**Comment by bago** [comment]
@lkarsten I think I "guessed" too much about proxy_protocol v2, sorry.

https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

> 7. Future developments
> 
> It is possible that the protocol may slightly evolve to present other
> information such as the incoming network interface, or the origin addresses in
> case of network address translation happening before the first proxy, but this
> is not identified as a requirement right now. Some deep thinking has been spent
> on this and it appears that trying to add a few more information open a Pandora
> box with many information from MAC addresses **to SSL client certificates**, which
> would make the protocol much more complex. So at this point it is not planned.
> Suggestions on improvements are welcome.

I know Apache HTTPD has an option to expose the client certification to the serving script (ExportCertData in SSLOptions directive) and I didn't know PP2 had a "predefined set of variables" instead of a key-value structure, sorry.

**Comment by daghf** [comment]
Hey

This is now in. See https://github.com/varnish/hitch/blob/master/hitch.conf.man.rst#client-verify--requiredoptionalnone
