### ISSUE TITLE
{backend-connect}: Cannot assign requested address

### ISSUE THREAD

**Issue by ffh-webadmin** [varnish/hitch#213]
We are using hitch 1.4.4 in conjunction with varnish 5.0.0 on an Ubuntu System. So far everything works fine. Only if we get some more requets per second some clients will get an "Empty Response". In these moments we will find the following lines in syslog:

Oct  9 10:01:35 cache1-vm hitch[18741]: 20171009T100135.652141 [18774] {backend-connect}: Cannot assign requested address
Oct  9 10:01:35 cache1-vm hitch[18741]: 20171009T100135.656940 [18772] {backend-connect}: Cannot assign requested address
Oct  9 10:01:35 cache1-vm hitch[18741]: 20171009T100135.657043 [18775] {backend-connect}: Cannot assign requested address
...

What does this mean? Is it a hitch or varnish related issue? 

Our setup is quite simple: 4 Domains with 4 certs.
````sh
# Listening
frontend = "[*]:443"
ciphers  = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
# TLS 1.0 wird gebraucht, damit alte Server (intranet-srv) eine Verbindung aufbauen können
tls-protos = TLSv1.1 TLSv1.2 TLSv1.0

# Send traffic to the Varnish backend using the PROXY protocol
backend        = "[::1]:6086"
write-proxy-v2 = on

# Number of processes
workers = 6

# List of PEM files, each with key, certificates and dhparams
pem-file = "/etc/hitch/certs/xyz.pem"
...
````
The file ulimit was set to 500.000.

Thanks!

**Comment by daghf** [comment]
Hi @ffh-webadmin 

This looks like an `EADDRNOTAVAIL` error, which means we ran out of available ephemeral ports.

Could you try bumping up the range in `/proc/sys/net/ipv4/ip_local_port_range`?

The file consists of two numbers, describing the low and high end of the available range. Setting it to something like `4096 65000` should be OK. 

You could also try setting `sysctl net.ipv4.tcp_tw_reuse` to 1, which should make the system quicker at reusing port numbers.

Please try that and let us know how it goes.

**Comment by ffh-webadmin** [comment]
Hi  @daghf,

thanks for the response. Here the port range:

root@cache2-vm:~# cat /proc/sys/net/ipv4/ip_local_port_range
32768   60999

I set it to 4096 65000 via /etc/sysctl.conf

We expect the next connection peak tomorrow morning...

I also added net.ipv4.tcp_tw_reuse = 1

With these information we found the following post: https://easyengine.io/tutorials/linux/sysctl-conf/ Are there any other important parameters for hitch?

**Comment by ffh-webadmin** [comment]
Adjusting the ip_local_port_range solved the problem! Thanks for the support. Perhaps this should be added to the docs?
