### ISSUE TITLE
hitch fails to start in CentOS 7 due to wrong "type" in systemd unit file

### ISSUE THREAD

**Issue by rsuarezsoto** [varnish/hitch#222]
Hi,

I'm running hitch 1.4.6 (package hitch-1.4.6-4.el7.x86_64 from EPEL). It won't start with a minimal configuration like this:

```
backend = "[127.0.0.1]:6086"
workers = 1
daemon = "on"
user = "hitch"
group = "hitch"
write-proxy-v2 = "on"

frontend = {
  host = "*"
  port = "443"
  pem-file = "/etc/hitch/hitch.pem"
  
}
```

Being "/etc/hitch/hitch.pem" a self-signed certificate for testing purposes.

The problem seems to be the systemd unit file: it uses "type=simple" instead of "type=forking". Changing this, hitch starts and behaves as expected.

**Comment by ingvarha** [comment]
This looks like downstream epel bugzilla entry 1467839;
https://bugzilla.redhat.com/show_bug.cgi?id=1467839

Can you follow up there, please.

Ingvar

**Comment by sfblaauw** [comment]
+1

**Comment by dmatetelki** [comment]
@denisbr : both debian & redhat systemd service files for hitch have `Type=forking` and they haven't been modified since 2015. What are your thoughts?

**Comment by denisbr** [comment]
@dmatetelki I did do some research into this, but stopped short of changing it mainly due to me not being able to reproduce the issue.

If you could have a look at it, and create a service file with ``Type=forking`` that works, we can definitely change it.

**Comment by dmatetelki** [comment]
@rsuarezsoto: @ingvarha is correct, please continue the discussion at the redhat bugzilla, as he is taking care of the packaging.
