### ISSUE TITLE
Why suggest "nobody" user?

### ISSUE THREAD

**Issue by gperciva** [varnish/hitch#236]
The default conf file suggests:
```
user = "nobody"
group = "nogroup"
```

My recollection is that using `nobody` is not recommended for daemons, since a security flaw in one daemon provides access to other daemons (i.e. reading/writing data files, viewing memory, sending signals).  I'm willing to add notes to the docs suggesting a `hitch` user (and group), if you think that would be a good addition.

**Comment by Dridi** [comment]
Bumping for today's bugwash, let's make sure to docfix this before the next release.
