### ISSUE TITLE
Hitch + http2 fails 

### ISSUE THREAD

**Issue by sonicseaweed** [varnish/hitch#237]
This will sadly be an incomplete bug report as I have not been able to pin down the exact error. 

We have found that when using Hitch 1.4.6 with http2 enabled on RHEL 7.4 (OpenSSL 1.0.2k) with Varnish 5.2.1 as backend (though the Varnish version seems to be irrelevant) some devices fail under certain circumstances. 

We know that there are at least two networks that produce the error. Neither have any firewall, nor any special rules that would impact the connection to the server. If we use Safari on an iPad on these networks, the connection will consistently fail with `kCFErrorDomainCFNetwork Code=303` (which apparently translates to `cfErrorHTTPParseFailure`). It is not always the same resources that fail and it seems more likely that large items (bundled JS, large images) are more prone to fail. It is almost as if there is a timeout that is exceeded. 

The error does not appear if we
- turn off http2. 
- use a different TLS termination such as Haproxy
- use the same Ipads on different networks (Our network managers have assured us that the connections we are using are not filtered or interfered with in any way)

The error appears
- All Ipads we have tested (5 different vintages) on these networks. Does not appear to matter if they are updated or not
- Same results on both IPv4 and IPv6
- consistently. If you reload enough times you may luck out and get all parts in the cache, but a clearing of the browser cache re-confirms the problem. 

How to reproduce
- No idea. Certain network connections make the problem obvious, but the rest work flawlessly. 

Our current hitch config:
```
frontend = {
    host = "*"
    port = "443"
}

backend = "[127.0.0.1]:6081"
pem-file = "[path to cert + key].pem"
ocsp-dir = "[path to oscp]/ocsp"
ocsp-resp-tmo = 10;
ocsp-connect-tmo = 4;
ocsp-verify-staple = on
tls-protos = TLSv1.0 TLSv1.1 TLSv1.2
ciphers = "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS:!3DES"

prefer-server-ciphers = on
ssl-engine = ""
workers = 4
backlog = 10000
keepalive = 3600
chroot = ""
user = "hitch"
group = "hitch"
quiet = on
syslog = off
syslog-facility = "local2"
daemon = off
write-ip = off
write-proxy-v1 = off
write-proxy-v2 = on
proxy-proxy = off
sni-nomatch-abort = off
alpn-protos = "h2,http/1.1"

```

With `quiet = off` we get the following from the client which doesn't differ from a functioning client.

```
2017-12-12T12:21:56.724790+00:00 [servername] INFO 20171212T122156.722839 [ 9473] [CLIENT_IP]:52013 :0 10:11 proxy connect
2017-12-12T12:21:56.725075+00:00 [servername] INFO 20171212T122156.722863 [ 9473] [CLIENT_IP]:52013 :0 10:11 ssl handshake start
2017-12-12T12:21:56.725234+00:00 [servername] INFO 20171212T122156.722874 [ 9473] [CLIENT_IP]:52013 :0 10:11 ssl client handshake revents=1
2017-12-12T12:21:56.725437+00:00 [servername] INFO 20171212T122156.724199 [ 9473] [CLIENT_IP]:52013 :0 10:11 ssl client handshake err=SSL_ERROR_WANT_READ
2017-12-12T12:21:56.761094+00:00 [servername] INFO 20171212T122156.760880 [ 9473] [CLIENT_IP]:52013 :0 10:11 ssl client handshake revents=1
2017-12-12T12:21:56.761348+00:00 [servername] INFO 20171212T122156.761148 [ 9473] [CLIENT_IP]:52013 :0 10:11 NPN/ALPN protocol: h2
2017-12-12T12:21:56.761514+00:00 [servername] INFO 20171212T122156.761157 [ 9473] [CLIENT_IP]:52013 :0 10:11 ssl end handshake
2017-12-12T12:21:56.761687+00:00 [servername] INFO 20171212T122156.761336 [ 9473] [CLIENT_IP]:52013 :44704 10:11 backend connected
```

I can find no issues when looking at the varnishlog, nor when comparing tcpdumps in wireshark. From the server side everything reports as A-OK. I was inclined to believe that it was a network error, but I found no proof of that being the case, and since using haproxy with the same certificate and varnish backend produces a working solution, i'll submit this as an issue.

**Comment by gquintard** [comment]
can you give use the varnishd command you are using? (``ps aux | grep varnishd``)

**Comment by sonicseaweed** [comment]
/usr/sbin/varnishd -P /var/run/varnishDirector/varnish.pid -f /etc/varnish/default.vcl -a :80 -a :6081,PROXY -T : -t 120 -s malloc,5G -n director_varnish -l 160m -p thread_pool_min=200 -p thread_pool_max=1000 -p thread_pool_timeout=900 -p feature=+http2

**Comment by klenan** [comment]
https://github.com/varnishcache/varnish-cache/issues/2473 might relate, have you tried a Varnish version with those patches applied? It's in master but not the 5.2.1 release.

**Comment by sonicseaweed** [comment]
I have not tried this yet. But I will attempt it now

**Comment by sonicseaweed** [comment]
Thank you @klenan. Building varnish from the master branch in the repository and using it with hitch works! I guess this was a non-issue.

Is there a varnish release with this bug corrected available in the near future?

**Comment by daghf** [comment]
@sonicseaweed

A release containing that fix will probably not be released until March 15.

In the meantime, we have weekly Varnish packages if you'd like to give that a try, https://packagecloud.io/varnishcache/varnish-weekly
