### ISSUE TITLE
Consider allowing for no default certificate, killing the connection instead

### ISSUE THREAD

**Issue by atomt** [varnish/hitch#24]
This is more an idea, may or may not be useful. It's 3AM so I may be brainfarting. There are other ways to deal with this, say dedicating a IP for sites supporting TLS.

An ability to drop the connection rather than choosing a default cert if there is no matching certificate can be useful when you share an IP address with both TLS and non-TLS sites. The connection would have to be killed off before the cert is exchanged, of course. This would stop people from randomly adding https in their address bar and get a privacy warning -- and actually work around a "feature" in Apple Mail. To avoid problems with non-SNI clients one could only have this policy applied if SNI is sent.

Rather TLS would simply be rendered "unavailable", which it was probably meant to be anyway.

Apple Mail has this quirk where when you set up a new account it will take the domain part of the address, and attempt HTTPS on port 443 on it to see if it can auto configure Exchange even if all you want to set up is IMAP/SMTP.
If that domain has no certificate, but the IP serves up a mismatched cert, it will present a big privacy warning that users will confuse with their email being MITM-ed (well, if they are "smart").

In any case avoidable certificate warnings is no good.

**Comment by daghf** [comment]
Hi

The rfc ([link](https://tools.ietf.org/html/rfc6066#section-3)) says:

>  If the server understood the ClientHello extension but does not recognize the server name, the server SHOULD take one of two actions: either abort the handshake by sending a fatal-level unrecognized_name(112) alert or continue the handshake.

Hitch curently takes the second approach, but adding an option for the first approach (abort the handshake) is probably something we'll be willing to do.

I'll leave this open and will revisit it at a later point.

**Comment by daghf** [comment]
Hi again,

I've now added an --sni-nomatch-abort option, which will make hitch abort the handshake and terminate the connection when presented with an unrecognized SNI server name.

Please test and feel free to reopen if you run into any issues.
