### ISSUE TITLE
Feature request: /etc/hitch/cert.d/ support

### ISSUE THREAD

**Issue by lkarsten** [varnish/hitch#243]
Hi.

I'd like to request a new feature in Hitch: reading certificates (or configuration) from a directory, instead of having to enumerate them all in hitch.conf.

This could look like: `pem-file = "/etc/hitch/cert.d/*pem"` (reusing the old format, adding globbing)
or  a new directive like `pem-dir = /etc/hitch/cert.d/`.

The main use case is with Let's Encrypt.

Avoiding the `cat foo.key foo.crt > foo.pem` step as part of this would be even better. I haven't considered it in detail.

**Comment by gquintard** [comment]
the ``pem-file`` directives order is important though:

```
# SSL x509 certificate file. REQUIRED.
# List multiple certs to use SNI. Certs are used in the order they
# are listed; the last cert listed will be used if none of the others match
```

**Comment by Dridi** [comment]
> the `pem-file` directives order is important though:

Other products making use of drop-in directories but also requiring a specific load order usually load files in lexicographic order and document it as such.

Random picks on my current system:

```
$ ls -1 /usr/lib/systemd/system-preset/
90-default.preset
90-systemd.preset
99-default-disable.preset
$ ls -1 /etc/sysctl.d
50-obfuscated.conf
99-sysctl.conf
$ sudo ls -1 /etc/polkit-1/rules.d
49-obfuscated.rules
50-obfuscated.rules
ls -1 /etc/udev/rules.d
60-obfuscated.rules
70-obfuscated.rules
```

We could expect users to be familiar with this, and of course document how a drop-in directory would be loaded (eg. lex order, no subdirs, etc).

> Avoiding the `cat foo.key foo.crt > foo.pem` step as part of this would be even better. I haven't considered it in detail.

I'm not taking that point into account in this comment.

**Comment by lkarsten** [comment]
This could perhaps just be `hitch.conf` like this:
```
pem-file = "/etc/hitch/cert.d/*.pem"
pem-file = "/etc/hitch/default.pem" # Default certificate last.
```

and as Dridi just pointed out, if ordering is important on the installation, using `00-foo.pem` and `99-bar.pem` should do the trick.

I must admit I don't care much about non-SNI clients at this point.

But I think the most important part here is aligning it for smooth operation with Let's Encrypt, which I need to look up the details on.

**Comment by gquintard** [comment]
Was just pointing that detail out, as long as the ordering is stable and clear to the user, all good.

**Comment by lkarsten** [comment]
Hello again.

Having spent some more time on this, I think what I need would look like this:
```
frontend = "[127.0.0.1]:8443"
[..]
pem-file = "/etc/letsencrypt/live/*/privkey.pem"
pem-file = "/etc/letsencrypt/live/*/fullchain.pem"
pem-file = "/etc/hitch/fallback.pem"   # for non-SNI clients/unknown domain names.
```

This requires that private keys can be loaded by a separate pem-file line than the cert+intermediate for it. I can't remember if this is supported now?

This allows for full automated Let's Encrypt integration, with a simple SIGHUP to reload when something has changed.

**Comment by radriaanse** [comment]
Hi, we would like to have this also.
Since the last reply has been a while, is anyone already/still working on this?

**Comment by lkarsten** [comment]
There is some code in master now that can load directories. It looks to be based on PR #281 .

However, I don't think this implementation has been given enough thought, under the following assumption:  The majority of systems will have a small set of certificates and will be running certbot.

With the current implementation you seem to have to:
```
pem-dir = "/etc/letsencrypt/live/example.com/"
pem-dir = "/etc/letsencrypt/live/example.org/"
[..]
```

What I think I want is:
```
pem-dir = "/etc/letsencrypt/live/*/fullchain.pem"
pem-dir = "/etc/letsencrypt/live/*/privkey.pem"
```

The current implementation gives this error (note it adds the final slash by itself):
```
Dec 10 13:22:36 lima hitch[4551]: Unable to open directory '/etc/letsencrypt/live/*/fullchain.pem/': No such file or directory
```

I don't see any distinct upside to forcing the user to duplicate the list of domain names that should be available in yet another config file?

A generic "all certs on disk" hitch.conf should suffice, I think?

**Comment by lkarsten** [comment]
Now that 1.5.0 was released, I think the ship has sailed on adressing the problems raised in the last comment.

Good enough for your use cases, I suppose. I'll close this issue now.
