### ISSUE TITLE
Feature request: Run script when an unknown SNI host is seen.

### ISSUE THREAD

**Issue by lkarsten** [varnish/hitch#244]
Hello.

I'd like to request a new feature in Hitch: If an unknown SNI host is seen, given some limitations, fork and run a pre-defined script.

This opens for automatically having certbot/something make a key+certificate for the new domain when it is needed, giving us ~zero configuration TLS.

In the configuration file, it could perhaps look like:
```
default-sni-hook = "/usr/local/bin/make-cert.sh %h"
```
where `%h` expands to the SNI hostname seen. Other variables/expansions for socket/"server" IP and port, and client IP would also be useful.

I think it should happen on connection establishment, after SNI decision has been done, before data is being exchanged. As early as possible, to get the certificate in place as soon as possible. The first connection(s) will get the default certificate until (if ever) `make-cert.sh` has completed and SIGHUP-ed hitch.

Doing this correct probably would need some rate limiting (max n calls per minute, max 1 initiation per source IP per time slot, or something like that), but that should be doable. 

The forked subprocess should of course check that the SNI name resolves to something sensible before doing its thing.

A possible extension is to let the script/subprocess return a status code (ok / refused / blacklist) on exit, but that may be over-engineering it a bit.

**Comment by lkarsten** [comment]
Let's Encrypt have added a TLS-only validation method, which I think is a good fit for this.

https://tools.ietf.org/html/draft-ietf-acme-acme-03#section-7.3

The only problem is that they require key + certificate generation inline, so the method described above needs to block the initial response instead of working in a forked child process.

**Comment by lkarsten** [comment]
Hi.

Doesn't seem like there was must interest in this, and for my use case I solved it in a different way. I'll close this issue now.

**Comment by Dridi** [comment]
I think this would open a DoS vector where untrusted clients could make a hitch server continually run instances of the script with random authorities. Something better handled outside of TLS traffic in my opinion.
