### ISSUE TITLE
Add --proxy-proxy2 for proxy protocol version 2?

### ISSUE THREAD

**Issue by secretmike** [varnish/hitch#249]
Amazon's Network Load Balancer only supports proxy protocol version 2 when talking to services. When using proxy protocol version 2, it also sends through some custom data for VPC endpoints that would be useful to the end application.

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#proxy-protocol

It would be great if hitch supported passing through proxy protocol 2 like it does with version 1.

Perhaps a `--proxy-proxy2` option?

If this makes sense I'm happy to put together a PR.

**Comment by Dridi** [comment]
Hello @secretmike,

I could have sworn I had replied to you on Monday but either my comment is gone or I screwed up and forgot. We'd be delighted to review a pull request for proxy v2 forwarding, so thank you for stepping in!

**Comment by Exocomp** [comment]
@secretmike @Dridi 

I'm also looking for a --proxy-proxy2 option to work with receiving and sending of proxy protocol version 2.  Any progress made on it as of yet?  :)

**Comment by JimmyBeats** [comment]
@secretmike @Dridi Is this still on the roadmap?

**Comment by daghf** [comment]
This is in now, and will be in the next release.

I did it slightly different from adding the suggested ``--proxy-proxy2``. Instead I augmented the current ``--proxy-proxy`` to auto-detect PROXY version and handle both cases.

**Comment by JimmyBeats** [comment]
Fantastic news! Thank you @daghf !
