### ISSUE TITLE
Provide default secure configuration

### ISSUE THREAD

**Issue by FredericJacobs** [varnish/hitch#25]
Hitch looks great. What is Hitch's philosophy on cipher suites configuration?

I believe it would be good to provide a default configuration with strong defaults. I don't think any sysadmin should make a personal assessment of what cipher suite to use.

I think the default configuration should at least use PFS cipher suites only and have absolutely no RC4 or weak DHs.

I can do a pull-request with a document set of cipher suites if that's something you would be interested in.

**Comment by lkarsten** [comment]
Hi, and thanks for the feedback.

I agree with defaulting to strong ciphers, as long as we supply commented-out examples on how to increase compatibility for older browsers/clients.

A patch/PR would be a nice starting point.

**Comment by ktk** [comment]
Would be nice indeed, I tested my hitch instance on [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=gont.ch&hideResults=on), defaults currently get a B. So there is room for improvement :)

**Comment by lkarsten** [comment]
Hi.

Thanks for bringing this up again. We actually documented and fixed this a while ago, but I guess I forgot to reply here.

See https://github.com/varnish/hitch/blob/master/docs/configuration.md for configuration documentation, including a cipher list string that give an A rating with Qualys/SSLlabs.

This configuration is currently running on https://hitch-tls.org , the SSL test site should confirm this: https://www.ssllabs.com/ssltest/analyze.html?d=hitch-tls.org

We're evaluating further steps to get up to A+, but there is no time frame as it is now.

**Comment by ktk** [comment]
Ah great tnx, will try that out. Any plans on making that default sooner or later?
