### ISSUE TITLE
Feature: Support for multiple backends

### ISSUE THREAD

**Issue by andrisvasers** [varnish/hitch#250]
If one of the varnish instances crashes and restarts, it's time consuming process when varnish charges all required data on heavy loaded sites. 
It would be great feature to define multiple backend servers and make load balancing/fail-over to other backend/-s.

**Comment by lkarsten** [comment]
I am against adding this to Hitch.

The rationale is that it opens a whole new field of new problems, like how to health check backends and which load balancing algorithm to use.

I solely run Hitch on the same machine/vm as Varnish, which may influence my thinking.

**Comment by klenan** [comment]
There are multiple ways for (redundant) load-balancing setup, even within [Varnish](
https://www.varnish-software.com/glossary/what-is-load-balancing/) itself.

Adding such functionality to hitch seems completely out of scope.
