### ISSUE TITLE
Wrong certificate being selected with multiple pem-files inside multiple frontends

### ISSUE THREAD

**Issue by Exocomp** [varnish/hitch#251]
I have a config file with the following settings:

```
frontend = {
        host = "10.0.0.10"
        port = "443"
        pem-file = "/etc/hitch/ssl/api.server.com"
        pem-file = "/etc/hitch/ssl/www.server.com"
}

frontend = {
        host = "10.0.0.11"
        port = "443"
		pem-file = "/etc/hitch/ssl/api.server.com"
}
```

Goal: 
Host 10.0.0.10 is for clients with SNI support, as you can see there are two pem files.  Host 10.0.0.11 is for clients with no SNI support and just to be used with one pem file.

Problem:
When I make a request to "www.server.com" going to 10.0.0.10 it sometimes returns the api.server.com certificate and other times it returns the www.server.com certificate (same request).  Why?  This causes a problem because the request is for www.server.com but it is returning certificate api.server.com?

If I move the two "pem-file" files outside of the two frontend blocks then it work fine with no issues.  However, since 10.0.0.11 is only serving api.server.com for clients with no SNI support I don't want to do that.  

Per the documentation on pem-file:  https://github.com/varnish/hitch/blob/master/hitch.conf.man.rst#pem-file--string

"This option is also available in a frontend declaration, to make a certificate only available for a specific listen endpoint."

Why does this configuration cause a problem ?

**Comment by klenan** [comment]
Fixed in master, see #194.

**Comment by Dridi** [comment]
@klenan thanks again for your help!

@Exocomp can you try building hitch from source and reopen this issue if it still happens?

**Comment by Exocomp** [comment]
Thanks guys, I tested in 1.4.7 and it is fixed.  :)
