### ISSUE TITLE
AC_MSG_ERROR with 1.4.6 tarball on Ubuntu Artful

### ISSUE THREAD

**Issue by lkarsten** [varnish/hitch#252]
Issue: When trying to build ubuntu package of 1.4.6 from tarball, it builds nicely on trusty but fails on 17.10 artful.

Expected: a more recent autoconf should work fine.

```
dpkg-buildpackage: info: source package hitch
dpkg-buildpackage: info: source version 1.4.6-0+daily+20180306.100742
dpkg-buildpackage: info: source distribution artful
 dpkg-source --before-build hitch-1.4.6
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean
   dh_auto_clean
   dh_autoreconf_clean
   dh_clean
 debian/rules build
dh build
   dh_update_autotools_config
   dh_autoreconf
configure.ac:46: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
dh_autoreconf: autoreconf -f -i returned exit code 1
debian/rules:22: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
--------------------------------------------------------------------------------
Build finished at 20180306-0910
```
Workaround on the packaging side was to call `dh $@ --without-autoreconf` (ish) in `debian/rules`.

This can be reproduced by having a ubuntu 17.10 vm with pre-reqs installed and the 1.4.6 tarball:
 
```
$ cd hitch-1.4.6/
~/fo/hitch-1.4.6$ autoreconf -v -f
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:46: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

Is there something missing in the tarball that makes autoconf fail?

**Comment by Dridi** [comment]
What's probably missing is the package that contains the file that defines `AC_MSG_ERROR`.

However, since we ship dist archives already bootstrapped, the simplest is to not require autotools at packaging time and start at the `./configure` step directly.

**Comment by lkarsten** [comment]
Re skipping reconf during normal builds, I agree. That is simplest.

The Debian packaging overlords have some explanation on why they do it by default:

> Autoreconfing on build is good practice in Debian. There used to be good reasons to stick with the autotools files shipped in the upstream tarball (mostly incompatibility with newer versions), but these days good forward compatibility and the advantages of getting the latest updates for new architectures or other fixes means that autoreconfing on build should be the default in packages.

(from https://wiki.debian.org/Autoreconf )

**Comment by Dridi** [comment]
On my non-Debian system `AC_MSG_ERROR` is defined in `/usr/share/autoconf/autoconf/general.m4` as an alias to `AS_ERROR`. The latter being apparently defined in `/usr/share/autoconf/m4sugar/m4sh.m4` also provided by the autoconf package:

```
$ rpm -qf /usr/share/autoconf/{autoconf/general,/m4sugar/m4sh}.m4
autoconf-2.69-25.fc27.noarch
autoconf-2.69-25.fc27.noarch
```

Is `m4sh.m4` correctly installed in your build environment?

**Comment by lkarsten** [comment]
Hi.

This system has autoconf version 2.69.
```
$ find / -name m4sh.m4
/usr/share/autoconf/m4sugar/m4sh.m4
$ dpkg -S m4sh.m4
autoconf: /usr/share/autoconf/m4sugar/m4sh.m4
autoconf: /usr/share/autoconf/m4sugar/m4sh.m4f
```

`/usr/share/autoconf/autoconf/general.m4` has this line, which I think is the definition you describe:
"m4_copy([AS_ERROR],   [AC_MSG_ERROR])". 

I also see this on a separate Debian stretch system with autoconf 2.69:
```
~/hitch$ autoreconf
configure.ac:46: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
~/hitch$ ./bootstrap
+ set -o errexit
+ aclocal -I .
+ autoconf
+ autoheader
+ mkdir -p build-aux
+ automake --add-missing --foreign
~/hitch$ ./configure --quiet
~/hitch$ echo $?
0
```

**Comment by Dridi** [comment]
Can you somehow teach `dh_autoreconf` to run `autoreconf -I .` ?

**Comment by lkarsten** [comment]
Yes, that works. Thank you.

Related commit: https://github.com/lkarsten/ppa-hitch/commit/59ef85b123a5a7950b8df102b01e6e2d3192da68

Closing issue.
