### ISSUE TITLE
Config file ciphers= ignored?

### ISSUE THREAD

**Issue by lkarsten** [varnish/hitch#255]
Issue: `ciphers = "foo"` is accepted by hitch on startup. Connection is using TLS_AES_256_GCM_SHA384.

Expected: an error message.

**Comment by klenan** [comment]
I cannot reproduce this, neither with 1.4.6 nor 3fd374d. Both `ciphers = "foo"` in **hitch.conf** and `-c foo` on the command line fail as expected:

```
# grep ^ciphers $config
ciphers = "{core} hitch 1.4.6 starting
20180326T172617.361044 [16090] {core} SSL_CTX_set_cipher_list: error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match
# ./src/hitch --config=$config -c foo
20180326T172628.226670 [16118] {core} hitch 1.4.7 starting
20180326T172628.228815 [16118] {core} SSL_CTX_set_cipher_list: error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match
foo"
```

**Comment by lkarsten** [comment]
Hi.

This was probably just me being confused or stupid. I haven't run into it afterwards, and since nobody else has chimed in, it is probably fine.

I'll close this issue now.
