### ISSUE TITLE
Whats the "official/latest" release?

### ISSUE THREAD

**Issue by sheesupport** [varnish/hitch#259]
Just confused: https://hitch-tls.org/ shows hitch-1.4.6.tar.gz while
https://github.com/varnish/hitch/releases shows hitch-1.4.7 as latest 
release. So, what is the "official" release? Thanks?

**Comment by daghf** [comment]
Hi

1.4.7 turned out to have some problems, so its rollout was stopped. We're planning a 1.4.8 to remedy this in the next few days.
