### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [varnish/hitch#26]
[An extra null pointer check is not needed](http://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Do I need to check for NULL before free(p)?") in a function like "[config_destroy](https://github.com/varnish/hitch/blob/e16d6430dda458b2fb423f007307fe9f9a9fae57/src/configuration.c#L184 "Update candidate")".

**Comment by daghf** [comment]
Thanks.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/varnish/hitch/commit/49c4e8dd5ad7840c096c1bd5393f5659cbd6b073 "Deletion of a few pointer checks").
