### ISSUE TITLE
Hitch frontend binds to incomplete IPv6 address

### ISSUE THREAD

**Issue by da2x** [varnish/hitch#272]
Let’s confirm we have the desired IPv6 address …
```
$ ip a
[…]
    inet6 2a01:a:b:c::aaaa/64 scope global deprecated 
       valid_lft forever preferred_lft 0sec
```
Let’s configure Hitch to use it …
```
frontend = {
  host = "2a01:a:b:c::aaaa"
  port = "443"
  pem-file = "/etc/hitch/bundle.pem"
}
```
And finally confirm that Hitch binds to the right— wait, where did the last part of the IPv6 address go?
```
$ netstat -n --listen | grep 443
tcp6       0      0 2a01:a:b:c:::443 :::*                    LISTEN
```

Ubuntu 18.04 LTS, Hitch 1.4.4

**Comment by gquintard** [comment]
use brackets:

```
 host = "[2a01:a:b:c::aaaa]"
```

If should probably be made cleared in the docs though

**Comment by da2x** [comment]
> use brackets:

That doesn’t work. Hitch won’t start.

    {getaddrinfo-listen}: [[2a01:a:b:c::aaaa]]:443: Temporary failure in name resolution

Seems like brackets are added automatically and duplicated when I manually add them.

**Comment by klenan** [comment]
IPv6 listening addresses work as expected with recent 1.4.8, please update.

**Comment by da2x** [comment]
> IPv6 listening addresses work as expected with recent 1.4.8, please update.

It does indeed. However, 1.4.4 is what is shipping in the recently released Ubuntu LTS so that is what everyone will be using for years. Maybe reach out to Debian packaging and ask them to update? Even Debian unstable still ships with 1.4.4. (Also, the packaging is kind of weird and difficult to configure.)

**Comment by klenan** [comment]
Ubuntu/Debian is not everyone.

This is a downstream issue; ask the respective package maintainers to ship newer releases or backport fixes.

**Comment by Dridi** [comment]
And in the case of an LTS, the maintainer should really follow releases closely because 1) Hitch is a sensitive product and 2) we aren't planning to break configuration in the foreseeable future.

**Comment by da2x** [comment]
I’ve actually asked the Debian maintainer to update six months ago but didn’t receive a reply.

Maybe it isn’t such a big issue. Hitch only has [14 users on Debian](https://qa.debian.org/popcon.php?package=hitch) and [3 on Ubuntu](https://popcon.ubuntu.com/by_inst) according to their respective deb popcons. (I believe Ubuntu enabled popcon by default for 18.04 so the number really should have been higher if there were more users.)

**Comment by lkarsten** [comment]
@da2x What is up with the bad attitude? Use hitch or not, it is your own choice, but please be respectful. It is free and you get to keep all the pieces if it breaks for you.

If you can help out, for example by becoming a Debian maintainer and fixing this, that would be awesome.

I'm running a Ubuntu PPA for bionic on https://launchpad.net/~lasse-karstensen/+archive/ubuntu/hitch . If that helps you/someone, and you're brave enough, feel free to use it. I'll update it when I or a customer of mine needs it. It has 1.4.8.

**Comment by Dridi** [comment]
@lkarsten, I haven't felt a bad vibe from anyone in this ticket (maybe too much enthusiasm?)

@da2x, did you open a ticket or reach out directly to the maintainer? From my experience on Fedora there may be co-maintainers so a ticket could have more chances to get noticed than a direct email. Thank you for reaching out downstream in the first place! That being said, I haven't seen @ssm for a while on IRC and I also had questions for him (unrelated to Hitch).

**Comment by daghf** [comment]
Looks like the issue here is taken care of in master. Closing.
