### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by mimez** [varnish/hitch#274]
Hey!

we've been using varnish for a long time. its very cool and we like it. but nowadays ssl-sites are very fancy and due to the fact that varnish does not support ssl, we had to search for a solution and came up with hitch. we configured it in our test environment and everything seemed to be fine. but now on production we have a sporadic connection error.

**Error**

Sometimes there is a connection failure. By requesting the website in the browser it appears a typical connection-error. We broke it down and can reproduce it by doing an apache bench. sometimes the benchmark fails like this:

```
ab -n 1000 -c 10 https://www.domain.de/
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking www.domain.de (be patient)
SSL read failed (5) - closing connection
SSL read failed (5) - closing connection
SSL read failed (5) - closing connection
SSL read failed (5) - closing connection
SSL read failed (5) - closing connection
SSL read failed (5) - closing connection
SSL read failed (5) - closing connection
SSL read failed (5) - closing connection
SSL read failed (5) - closing connection
SSL read failed (5) - closing connection
SSL read failed (5) - closing connection

Test aborted after 10 failures

apr_socket_connect(): Operation already in progress (37)
Total of 13 requests completed
```

But sometimes everything goes fine and apache bench does not break:

```
ab -n 1000 -c 10 https://www.domain.de/path
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking www.domain.de (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:
Server Hostname:        www.domain.de
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES128-GCM-SHA256,2048,128
TLS Server Name:        www.domain.de

Document Path:          XXXX
Document Length:        1654 bytes

Concurrency Level:      10
Time taken for tests:   8.242 seconds
Complete requests:      1000
Failed requests:        884
   (Connect: 0, Receive: 0, Length: 884, Exceptions: 0)
Total transferred:      2108761 bytes
HTML transferred:       1655338 bytes
Requests per second:    121.33 [#/sec] (mean)
Time per request:       82.421 [ms] (mean)
Time per request:       8.242 [ms] (mean, across all concurrent requests)
Transfer rate:          249.86 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       18   52  42.4     54    1299
Processing:     6   30  14.5     26      80
Waiting:        6   27  13.3     24      69
Total:         30   82  42.5     81    1335

Percentage of the requests served within a certain time (ms)
  50%     81
  66%     83
  75%     85
  80%     85
  90%     91
  95%     97
  98%    113
  99%    122
 100%   1335 (longest request)
```

The strange thing is: in any case (error or not) the website is not available (connection error) while doing the benchmark and even a telnet to 443 does not work:

```
telnet domain.de 443
Trying XXX.XX.128.208...
telnet: connect to address XXX.XX.128.208: Connection refused
telnet: Unable to connect to remote host
```

It seems that there is a correlation to the load. if there is no load, everything is fine. by decreasing the concurrent connections we can connect to the site. but on load we cant connect :(

Sidenote: sometimes we get in the log-file this 

```
20180704T185815.576968 [12835] {backend} Socket error: Connection reset by peer
```

**Our Setup**

We have following components:

- Hitch (TLS-Proxy)
- Varnish (Cache)
- Lighttpd (HTTP-Backend with PHP and PostgreSQL)

Our hitch-config is basically this:

**Config**

```
frontend = {
    host = "XXX.XX.128.208"
    port = "443"
}

backend = "[127.0.0.1]:6086"
workers = 4
write-proxy-v2 = on

daemon = on
user = "nobody"
group = "nogroup"
ocsp-dir = ""

pem-file = "XXX"

tls-protos = TLSv1.0 TLSv1.1 TLSv1.2
prefer-server-ciphers = on
...
```
does anyone have clue what is the problem here?

cheers
michael

**Comment by mimez** [comment]
Okay... its not a hitch problem at all. its a linux problem. we fixed this issue by increasing the limits:

```
sysctl -w net.netfilter.nf_conntrack_max=131072
echo 32768 > /sys/module/nf_conntrack/parameters/hashsize
```

**Comment by Dridi** [comment]
Reopening for next bugwash: it might be useful to document this somewhere, for example the wiki.

Thanks for reporting both your symptoms and solution!

**Comment by obliadp** [comment]
For a web-facing server that only serves web traffic (i.e. varnish), I would probably opt to blacklist the nf_conntrack module altogether. I can't think of a good reason to have a stateful firewall on a web server.

See f.i. https://wiki.debian.org/KernelModuleBlacklisting for an example.

**Comment by Dridi** [comment]
Added to the wiki's FAQ.
