### ISSUE TITLE
Hitch does not start, CentOS7, varnish cashe and lets encrypt.

### ISSUE THREAD

**Issue by Serge04** [varnish/hitch#275]
I was already having apache with varnish cache before, than I have installed Hitch and letsencrypt as here [](https://docs.varnish-software.com/tutorials/hitch-letsencrypt/
)

but hitch does not start 

`systemctl status hitch
● hitch.service - Network proxy that terminates TLS/SSL connections
   Loaded: loaded (/usr/lib/systemd/system/hitch.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2018-07-12 09:35:17 CEST; 8min ago
  Process: 6585 ExecStart=/usr/sbin/hitch --pidfile=/run/hitch/hitch.pid --config=/etc/hitch/hitch.conf (code=exited, status=1/FAILURE)
 Main PID: 4736 (code=exited, status=1/FAILURE)

Jul 12 09:35:17 server.net systemd[1]: Starting Network proxy...
Jul 12 09:35:17 server.net systemd[1]: hitch.service: control...
Jul 12 09:35:17 server.net systemd[1]: Failed to start Networ...
Jul 12 09:35:17 server.net systemd[1]: Unit hitch.service ent...
Jul 12 09:35:17 server.net systemd[1]: hitch.service failed.
Warning: hitch.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Hint: Some lines were ellipsized, use -l to show in full.`

hitch.service
`[Unit]
Description=Network proxy that terminates TLS/SSL connections
After=syslog.target network.target

[Service]

-#
-# If you want to make changes to this file, please copy it to 
-# /etc/systemd/system/hitch.service and make your changes there.
-# This will override the file kept at /lib/systemd/system/hitch.service
-#
-# Configuration may be done in /etc/hitch/hitch.params
-#

PIDFile=/run/hitch/hitch.pid

-# Maximum size of the corefile. 
LimitCORE=infinity

RuntimeDirectory=hitch
Type=simple
PrivateTmp=true
ExecStart=/usr/sbin/hitch --pidfile=/run/hitch/hitch.pid --config=/etc/hitch/hitch.conf
ExecReload=/usr/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target`

hitch.conf
`-# Run 'man hitch.conf' for a description of all options.

frontend = {
    host = "*"
    port = "443"
}
backend = "[127.0.0.1]:6086"    # 6086 is the default Varnish PROXY port.
workers = 4                     # number of CPU cores

daemon = on

-# We strongly recommend you create a separate non-privileged hitch
-# user and group
user = "hitch"
group = "hitch"

-# Enable to let clients negotiate HTTP/2 with ALPN. (default off)
-# alpn-protos = "h2, http/1.1"

-# run Varnish as backend over PROXY; varnishd -a :80 -a localhost:6086,PROXY ..
write-proxy-v2 = on             -# Write PROXY header

pem-file = "/etc/letsencrypt/live/sample.com/fullchain.pem"`

Changing type=simple to type=forking in /usr/lib/systemd/system/hitch.service
as written here [](https://bugzilla.redhat.com/show_bug.cgi?id=1467839) did not help.

Has somebody idea what could it be? thanks in advance for replies.

PS: i have put "-" before "#" just in this thread now because of rext formating in original files are no "-" before "#"

**Comment by gquintard** [comment]
Hi,

to my knowledge we don't provide open-source packages for hitch, can you take that issue to your CentOS packager?

It seems to just be that systemd isn't aware that hitch is started as a dæmon, that's easy to fix (and you did), but there's nothing we can do from here.

Best regards,

**Comment by Dridi** [comment]
Summoning @ingvarha just in case before a definite close.

**Comment by Serge04** [comment]
@gquintard @Dridi Thank you for reply. I have already deinstalled hitch and put configured server with nginx (ssl)-> varnish -> apache.
