### ISSUE TITLE
Is it possible to set a "priority" for certificates?

### ISSUE THREAD

**Issue by wioxjk** [varnish/hitch#277]
Let me explain the reason:
I have many websites, the main website has a certificate issued for www.domain.com and domain.com - it is an EV certificate. We also have other subdomains like - db.domain.com, share.domain.com and so on that I want to use a wildcard certificate on.

I hope you understand my question, let me know.

**Comment by Dridi** [comment]
The priority is based on the order, so you can have your certificate for d.c and www.d.c followed by your wildcard certificate. The first one matching is used, so the broadest should be last. The very last one is the fallback certificate used even when nothing matches, unless you hit the bugs from #276.

**Comment by wioxjk** [comment]
Thanks @Dridi , you had been to great help :)
