### ISSUE TITLE
Raw performance

### ISSUE THREAD

**Issue by dugwood** [varnish/hitch#279]
Hello dear Varnish & Hitch team,

I've recently faced a downtime on one server, because of a TV appearance, and thought it was a PHP issue. But looking at the server during the spike taught me otherwise: the bottleneck was Hitch (o.O)

As Varnish was caching the URL that was mainly hit, PHP wasn't loaded at all. Neither was Varnish (~6% of the total CPU). The limitation came from Hitch, that was configured with 4 workers (threads). Happily for me, a few weeks ago it was set to 1.

Having 8 cores on the server, I've set up 8 workers on Hitch, but that doesn't seem right to me.

To my mind, Hitch is meant to be a lightweight tool, faster than Varnish (through PROXY v2), and of course faster than lighttpd-PHP-MySQL as the backend. But it seems to be a bottleneck (if the backend is correctly optimized).

I've done a local test, which is clearly wrong, but it shows the issue I think. The test is:
 - guest virtual machine running Hitch -> Varnish -> lighttpd + PHP (with caching in Varnish)
 - host machine running ApacheBench
(so that's very wrong as guest and host are the same physical machine, but that removes the LAN issue).

Configuration:
 - Hitch is configured with 1 worker, as in the default configuration, defaults to recommended ciphers (the package comes from Debian's stable, but I've done the same test with the latest Hitch, 1.4.8, and got the same results).
 - Varnish has caching enabled (confirmed in `varnishhist` with all requests going back in less than 0.1ms)
 - ApacheBench runs 10000 concurrent requests with 200 clients (note that testing with 2 or 20 clients gives more or less the same results).

Running against a 894 bytes PNG file (I've removed useless information):
> ab -H "Accept-Encoding: gzip" -n 10000 -c 200 $URL
Finished 10000 requests
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES256-GCM-SHA384,2048,256
TLS Server Name:        xxxxx.com
Document Path:          /resources/flag.png
Document Length:        894 bytes
Concurrency Level:      200
Time taken for tests:   12.885 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      14028898 bytes
HTML transferred:       8940000 bytes
Requests per second:    776.12 [#/sec] (mean)
Time per request:       257.692 [ms] (mean)
Time per request:       1.288 [ms] (mean, across all concurrent requests)
Transfer rate:          1063.29 [Kbytes/sec] received

So we achieved 776 req/s, not too bad.

Running on HTTP only now:
> ab -H "Accept-Encoding: gzip" -n 10000 -c 200 $URL
Finished 10000 requests
Server Port:            80
Document Path:          /resources/flag.png
Document Length:        894 bytes
Concurrency Level:      200
Time taken for tests:   0.923 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      14000000 bytes
HTML transferred:       8940000 bytes
Requests per second:    10835.09 [#/sec] (mean)
Time per request:       18.459 [ms] (mean)
Time per request:       0.092 [ms] (mean, across all concurrent requests)
Transfer rate:          14813.60 [Kbytes/sec] received

This time, thanks to Varnish's caching, we hit 10835 req/s.

Looking at `htop` during the HTTPS test:
![image](https://user-images.githubusercontent.com/5517743/44907126-3e8bc300-ad17-11e8-9b5a-2aadd69ed146.png)
Hitch consumes about 100% of one CPU (as it's set to use 1 worker), Varnish 22% of another CPU (I've see the same ratio in production during the spike, but with 4x100% for Hitch, and about 25% for Varnish).

After reading a bit, I've read that depends on the cipher selected. For example Google uses 128 bits ciphers as a default, which may be faster. Let's try that!

> SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES128-GCM-SHA256,2048,128
Requests per second:    792.25 [#/sec] (mean)

> SSL/TLS Protocol:       TLSv1.2,DHE-RSA-AES128-GCM-SHA256,2048,128
Requests per second:    151.94 [#/sec] (mean)

> SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES128-SHA256,2048,128
Requests per second:    737.46 [#/sec] (mean)

> SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES128-SHA,2048,128
Requests per second:    765.81 [#/sec] (mean)

> SSL/TLS Protocol:       TLSv1.2,AES128-GCM-SHA256,2048,128
Requests per second:    852.86 [#/sec] (mean)

> SSL/TLS Protocol:       TLSv1.2,AES128-SHA256,2048,128
Requests per second:    861.32 [#/sec] (mean)

> SSL/TLS Protocol:       TLSv1.2,AES128-SHA,2048,128
Requests per second:    878.33 [#/sec] (mean)

So the best one is 100 req/s higher, with lower security, that's about 13% increase in speed. Comparing to direct Varnish (HTTP), where there was (10835 - 775) / 775 = 1298% of speed increase.

Am I missing something, or SSL isn't that light because of SSL cipher computation? I've never thought that adding SSL could be my new bottleneck.

**Comment by p-id** [comment]
We had experienced the same issue in production environment under a bit of high load on Debian based deployment (xenial) on commodity dell hardware. The issue seems that even with higher number of workers the incoming requests always seem to end up being served by a single worker (usually the first worker) and only if the queue is close to full, the request gets routed to be served by next worker inline.

The workaround that we pushed for is part of documented in this issue https://github.com/varnish/hitch/issues/142 (removed the earlier reporting id) and here - https://github.com/varnish/hitch/pull/241 

The effective use of SO_REUSEPORT with creating separate socket descriptors for each of the worker process seems to work atleast for us in production environment since quite a while, though it might have hickups in configuration reloads as suggested during review for https://github.com/varnish/hitch/pull/241 but that's I guess is slightly less pleasant than 100% cpu utilization by a single worker.

**Comment by dugwood** [comment]
Thanks @p-id for your insights.

Here my test was on a single worker, but I see the same issue with multiple workers. For example, using 3 workers:
![image](https://user-images.githubusercontent.com/5517743/45018442-65553c80-b02a-11e8-8749-f09ad46a9179.png)

As you can see, all workers are full, and I'm achieving a raw 1949 req/s, divided by 3 that gives us 649 req/s/thread, which is not that far from the original 775 req/s for only one worker. Varnish is eating about 60% (the rest is used by `varnishncsa`, which explains the ~95% of the last CPU).

My issue is that if all workers are running at 100% CPU, and each worker handle about 500 req/s, then with 8 CPUs I'm limited to 4000 req/s. Comparing to Varnish's 10k req/s, that's a new bottleneck.

In your case, did you see only one worker running at 100% and the other ones running low on CPU? As I don't know if testing the #241 will help me or not.

**Comment by gquintard** [comment]
Hi,

I think this is very much a discussion for the varnish-misc mailing-list as I don't reckon this to be a bug. What you see is fairly in line with openssl limits.

Opening SSL/TLS connections is going to be slow, but reusing them should be be almost free.

**Comment by dugwood** [comment]
@gquintard Thanks Guillaume, that's exactly my question: if Hitch is supposed to be light, and I've also read about Varnish not implementing SSL (https://varnish-cache.org/docs/trunk/phk/ssl.html and https://varnish-cache.org/docs/trunk/phk/ssl_again.html), I would expect that Hitch is fast.

But it just seem to be light, and not fast because of SSL. When I read the description of the github's page:
> A **scalable** TLS proxy by Varnish Software
> hitch is a network proxy that terminates TLS/SSL connections and forwards the unencrypted traffic to some backend. It's designed to **handle 10s of thousands of connections efficiently** on multicore machines.

So it's quite strange to find out it's «slow».

But you're right, it's not a bug per say, rather a call for help on optimizing speed. There's nothing on the Wiki about it. Just some startup time issues with some OpenSSL versions.

Should I do another benchmark with other OpenSSL versions, if it's the bottleneck of Hitch itself? Did anyone ask about such issue, or run benchmarks?

If the Varnish mailing list is the right place to start, I'll close this for now and add useful information when I'll get some. Thanks for the suggestion.

**Comment by espebra** [comment]
@dugwood ``ab`` runs by default with HTTP keep alive disabled. Assuming you're running this default, can you please rerun the tests with keep alive enabled?

With TLS the initial handshake is by far the most expensive operation and without keep alive you'll do a new handshake for every request.

**Comment by dugwood** [comment]
Note to self: check that OCSP is working correctly, and run another benchmark. OCSP directory is currently empty, which sounds wrong to me.

**Comment by dugwood** [comment]
I'll close this as it seems that's only the SSL handshake overhead.

I've done some more tests, and the results are a bit different. For instance, I still have the ~700 req/s without keep-alive, but it increases to 11500 req/s with keep-alive.

I'm a bit lost for now... production gives 1900 req/s (without keep-alive) and 33000 req/s (with keep-alive) from a nearby server. So it sounds okay.

**Comment by dugwood** [comment]
Just to add some benchmark on `nginx`: https://cdn.wp.nginx.com/wp-content/uploads/2014/07/NGINX-SSL-Performance.pdf

> NGINX’s SSL performance scales with the number of cores available on the host server, until
other limits (typically bandwidth) are met, so an 8-core virtual machine could accept traffic from
over 1,000 new users per second and still have resources to spare.

So on my servers with 8 cores, and now 8 workers, that's about that with `hitch`.
