### ISSUE TITLE
Feature request: pem-folder

### ISSUE THREAD

**Issue by nklausen** [varnish/hitch#282]
Currently multiple pem files are supported by listing them one-by-one
```
pem-file = "/etc/tls/first-combined.pem"
pem-file = "/etc/tls/second-combined.pem"
```
This feature request is about adding support for multiple pem files, by adding a new feature "pem-folder".

The new feature would work like this
```
pem-folder = "/etc/tls/"
```
Which would be equivalent to writing pem-file for each pem file in the folder "/etc/tls/"

**Comment by Dridi** [comment]
The github tracker is not for feature requests, closing.

Otherwise, see #281
