### ISSUE TITLE
Please support configuration of + multiple ecdh curves.

### ISSUE THREAD

**Issue by nyov** [varnish/hitch#283]
nginx can do this:
https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ecdh_curve

https://github.com/nginx/nginx/blob/a50dec6d6ac480b70b4fdf51507a1eda8a015e1b/src/event/ngx_event_openssl.c#L1109-L1190

**Comment by daghf** [comment]
Hi

This should now be taken care of via ae8877fe8b0f6e5e1187d1a1d7872329a6f37fca

Regards,
Dag

**Comment by nyov** [comment]
Thanks! That's great news.
