### ISSUE TITLE
how to write the frontend parameter?

### ISSUE THREAD

**Issue by luckypoem** [varnish/hitch#286]
hi,

```
root@wh:~# hitch --ssl --ciphers="EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH" --backend=[localhost]:8118
No x509 certificate PEM file specified for frontend 'default'!
root@wh:~#
```

tks

**Comment by Dridi** [comment]
hi,

wiki: https://github.com/varnish/hitch/wiki
docs: https://github.com/varnish/hitch/tree/master/docs
manual: https://github.com/varnish/hitch/blob/master/hitch.man.rst

bye
