### ISSUE TITLE
ERROR building HITCH on debian

### ISSUE THREAD

**Issue by MacGeyer** [varnish/hitch#287]
Trying to build hitch on latest stable Debian 

./configure works like a charm

make
make  all-recursive
make[1] : on entre dans le répertoire « /usr/src/hitch-1.4.8 »
Making all in src/util
make[2] : on entre dans le répertoire « /usr/src/hitch-1.4.8/src/util »
  CC       parse_proxy_v2-parse_proxy_v2.o
  CCLD     parse_proxy_v2
make[2] : on quitte le répertoire « /usr/src/hitch-1.4.8/src/util »
Making all in src
make[2] : on entre dans le répertoire « /usr/src/hitch-1.4.8/src »
make  all-am
make[3] : on entre dans le répertoire « /usr/src/hitch-1.4.8/src »
  CC       libcfg_a-cfg_lex.o
cfg_lex.c: In function ‘yy_get_next_buffer’:
cfg_lex.c:900:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for ( n = 0; n < max_size && \
                  ^
cfg_lex.c:1683:3: note: in expansion of macro ‘YY_INPUT’
   YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
   ^~~~~~~~
  CC       libcfg_a-cfg_parser.o
  AR       libcfg.a
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
  CC       foreign/flopen.o
  CC       foreign/vas.o
  CC       foreign/vpf.o
  CC       foreign/vsb.o
  CC       foreign/vsa.o
  AR       libforeign.a
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
  CC       hitch-asn_gentm.o
  CC       hitch-configuration.o
  CC       hitch-hitch.o
In file included from /usr/include/openssl/ssl.h:933:0,
                 from configuration.h:12,
                 from hitch.c:74:
hitch.c: In function ‘make_ctx_fr’:
hitch.c:995:46: error: passing argument 4 of ‘SSL_CTX_ctrl’ discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  if (!SSL_CTX_set_tlsext_servername_arg(ctx, fr)) {
                                              ^
In file included from configuration.h:12:0,
                 from hitch.c:74:
/usr/include/openssl/ssl.h:1821:6: note: expected ‘void *’ but argument is of type ‘const struct frontend *’
 long SSL_CTX_ctrl(SSL_CTX *ctx, int cmd, long larg, void *parg);
      ^~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:808 : la recette pour la cible « hitch-hitch.o » a échouée
make[3]: *** [hitch-hitch.o] Erreur 1
make[3] : on quitte le répertoire « /usr/src/hitch-1.4.8/src »
Makefile:600 : la recette pour la cible « all » a échouée
make[2]: *** [all] Erreur 2
make[2] : on quitte le répertoire « /usr/src/hitch-1.4.8/src »
Makefile:527 : la recette pour la cible « all-recursive » a échouée
make[1]: *** [all-recursive] Erreur 1
make[1] : on quitte le répertoire « /usr/src/hitch-1.4.8 »
Makefile:361 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

dpkg -l |grep ssl
ii  libssl-dev:amd64              1.1.1-2+0~20181105132527.5+stretch~1.gbp90eb86   amd64        Secure Sockets Layer toolkit - development files
ii  libssl1.0.2:amd64             1.0.2l-2+deb9u3                                  amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64               1.1.1-2+0~20181105132527.5+stretch~1.gbp90eb86   amd64        Secure Sockets Layer toolkit - shared libraries
ii  openssl                       1.1.1-2+0~20181105132527.5+stretch~1.gbp90eb86   amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  ssl-cert                      1.0.39                                           all          simple debconf wrapper for OpenSSL

Same problem as : https://stackoverflow.com/questions/53613590/compilling-hitch-in-ubuntu-error-ssl-ctx-ctrl-discards-const-qualifier-from

**Comment by Dridi** [comment]
I'm afraid this bug belongs to the bison project, the workaround would be to add `-Wno-error` to your CFLAGS at configure time.

We are very much aware of this, that's why in our build system the generated code is built separately:

https://github.com/varnish/hitch/blob/7970705ff2db2ae81600e4cae3be69824fac5cea/src/Makefile.am#L51-L53

Whereas we explicitly turn warnings into errors for the code we write:

https://github.com/varnish/hitch/blob/7970705ff2db2ae81600e4cae3be69824fac5cea/src/Makefile.am#L72-L77

**Comment by ruionwriting** [comment]
I now see this error on versions 1.4.6 to 1.4.8 on Alpine 3.9. Alpine 3.8 is good but because I need to use a base image for DotNet based on the official one this is pain. Any update on this?

**Comment by Dridi** [comment]
@ruionwriting can you share with us how you build `hitch`? @MacGeyer never replied whether the suggested workaround was enough.

**Comment by MacGeyer** [comment]
Sorry,, I didn't give any feed back ...
YES i confirm that I could do it with : `make CFLAGS='-Wno-error'`

**Comment by Dridi** [comment]
@MacGeyer, thanks for confirming. @ruionwriting does the workaround work for you? I will eventually turn warnings into errors only for development, but I'd like to get #299 in first.
