### ISSUE TITLE
hitch 1.4.8 (on CentOS 7.6 x64) not recognizing .pem file

### ISSUE THREAD

**Issue by jtroan** [varnish/hitch#289]
I'm unable to get hitch 1.4.8 to load on my newly-built CentOS 7.6 server due to "No x509 certificate PEM file specified for frontend 'default'!"  (I also got a new SSL.)

I've asked for assistance on ServerFault / StackExchange (question number 946406 ? ), but the suggestions received haven't helped so far.

During troubleshooting, I pulled over copies of my hitch.conf and (expired, but functional) .pem from my existing 1.4.5 (CentOS 6.9 x64) server; 1.4.8 still failed with the same error.

(I'm very willing to help troubleshoot this problem. Thanks!)

**Comment by gquintard** [comment]
can you post your `hitch.conf` and the hitch command line you are using?

**Comment by celesteking** [comment]
supply `--config /meh/yourconfig.conf`. press :+1: if it worked.

**Comment by erangil** [comment]
It is not working still getting the same error

**Comment by daghf** [comment]
@erangil what version is this? Could you post your hitch.conf and command line options?

**Comment by erangil** [comment]
Hi Dag,

hitch version -  1.4.4
command - service hitch start
error - hitch[25724]: No x509 certificate PEM file specified for frontend 'default'!

**hitch.conf**

# Run 'man hitch.conf' for a description of all options.
pem-file = "/etc/ssl/hitch.pem"

frontend = {
    host = "*"
    port = "443"
}
backend = "[localhost]:8334"    # 6086 is the default Varnish PROXY port.
workers = 1                     # number of CPU cores

daemon = on
user = "nobody"
group = "nogroup"

# Enable to let clients negotiate HTTP/2 with ALPN. (default off)
# alpn-protos = "http/2, http/1.1"

# run Varnish as backend over PROXY; varnishd -a :80 -a localhost:6086,PROXY ..
write-proxy-v2 = on             # Write PROXY header

**hitch.service**

[Unit]
Description=hitch
After=syslog.target network.target


[Service]
Type=forking
#Restart=on-failure
LimitNOFILE=131072
Environment="HITCH_OPTIONS=--config /etc/hitch/hitch.conf"
EnvironmentFile=-/etc/hitch/hitch.environment
EnvironmentFile=-/etc/default/hitch
EnvironmentFile=-/etc/sysconfig/hitch
ExecStartPre=/usr/sbin/hitch -t $HITCH_OPTIONS
ExecStart=/usr/sbin/hitch --daemon $HITCH_OPTIONS

[Install]
WantedBy=multi-user.target

**Comment by daghf** [comment]
Hi @erangil 

It's a bit puzzling that it only complains when started via systemd. Do you happen to use any of those ``EnvironmentFile`` entries? Can you check if you have something in one of those that would override ``HITCH_OPTIONS``?

When you say you are unable to connecf from a browser, can you be more specific? Is the backend application configured to accept a PROXYv2 preamble?

Regards,
Dag

**Comment by erangil** [comment]
Hi @daghf,
I'm unable to connect thru https probably related to the CA that I installed on the chrome browser which is by the way the same CA that is used by hitch.
Hitch resides on AWS EC2 instance together with varnish and nginx.
This is what I get in hitch log:
hitch[24462]: {backend-connect}: Connection refused
I'm getting an empty response to my browser.
I tried to create a CA using let's encrypt but it failed since my domain is not registered as it is an AWS DNS

**Comment by daghf** [comment]
@erangil If the browser shows an empty page and not a certificate error, then the cert is likely fine.

The error you are seeing means Hitch is not able to reach your backend. Verify that the ``backend`` property in your hitch.conf is correct, and that you indeed have something listening on that endpoint.

You also have ``write-proxy-v2`` enabled, so the backend application also needs to be able to handle PROXYv2.

**Comment by erangil** [comment]
@daghf ,
This is the error I'm getting from the syslog:
Jun 24 07:29:46 ip-172-31-46-40 hitch[6576]: 84.229.214.187:63564 :0 11:12 Handshake failure: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
Jun 24 07:29:46 ip-172-31-46-40 hitch[29619]: {backend-connect}: Connection refused

**Comment by daghf** [comment]
@erangil That handshake error says the browser does not trust your certificate.

Also verify that Varnish's ``-a`` argument is configured using PROXY, e.g. ``-a localhost:8443,proxy``.

**Comment by erangil** [comment]
@daghf ,
I installed in chrome browser the same hitch.crt file that i've generated on hitch server.
What other options do I have to resolve this issue.
BTW,

I saw this warning on hitch server:
hitch: WARNING: {core} OpenSSL version mismatch; hitch was compiled with 1010007f, now using 1010100f.

**Comment by daghf** [comment]
Hi @erangil

Just installing a self-signed certificate in your browser's trust store won't work. You will need to create a root certificate, and have that be the issuer of the certificate you use for Hitch. You can then install the public part of the root certificate in the browser, and it should work.

I'm closing this issue now, seeing as it doesn't look like there are any bugs to be fixed here.
