### ISSUE TITLE
Support for dynamic TLS-Record sizing

### ISSUE THREAD

**Issue by azet** [varnish/hitch#29]
ref: https://www.igvita.com/2013/10/24/optimizing-tls-record-size-and-buffering-latency/

**Comment by lkarsten** [comment]
Hi.

Only actionable issues/bugs are kept here.
Feature requests are tracked in the wiki: https://github.com/varnish/hitch/wiki/Future-features

Please add it there if you feel like this is something we should do.

If strongly about this and want to do the work yourself, make contact and we'll help you get started.

**Comment by azet** [comment]
@lkarsten added to the future-features list. Quick question: what are considered actionable items?

In general hitch will be a TLS terminator for varnish - dynamic record sizing is advantageous for performance and page load, both things - I think - varnish cares strongly about.

**Comment by lkarsten** [comment]
Hi @azet 

Thanks for adding it.

Actionable items means bug reports and issues we have a concrete plan of fixing in the near future. 
Keeping the issue list brief means that we can include it in our weekly issue sweep and easily identify new bugs and fix them.

I want to avoid having page after page with open issues on stuff someone thought was a good idea at some point, but never had the will/time/skillset to implement. It doesn't serve anyone, only diminishes the usefulness of the bug tracker.

I've talked a bit with @daghf about it before, and dynamic buffer sizing would be a nice function to add. There are quite a bit of open questions though, like how the sizing algorithm should work. For most connections it should be easy (small req in, big response chunk out), but we have to handle other situations gracefully (meaning: without excessive cpu usage) as well.

If you want to give developing this a go, we're happy to help you get started. Come see us on the varnish irc channels.

**Comment by azet** [comment]
Hey, @lkarsten

> I want to avoid having page after page with open issues on stuff someone thought was a good idea at some point, but never had the will/time/skillset to implement. It doesn't serve anyone, only diminishes the usefulness of the bug tracker.
Yea, I know that from GitHub and other FOSS projects, it's annoying, totally understand. But some issues do make sense and some should be kept around (I'm ok with moving this to a future-feature list).

> I've talked a bit with @daghf about it before, and dynamic buffer sizing would be a nice function to add. There are quite a bit of open questions though, like how the sizing algorithm should work. For most connections it should be easy (small req in, big response chunk out), but we have to handle other situations gracefully (meaning: without excessive cpu usage) as well.
Could you go into more details on what you've thought about w.r.t. sizing algorithms and their implementation? Just interested, not sure I can help there.

> If you want to give developing this a go, we're happy to help you get started. Come see us on the varnish irc channels.
I'd really love to. But I'm currently busy with far too many projects, I may come back in time - wanted to contribute when I opened the issue but never got to it because of customers, research, pending tasks and other FOSS projects. :(
