### ISSUE TITLE
SSLLabs / other tools sometimes fail

### ISSUE THREAD

**Issue by robinbohnen** [varnish/hitch#296]
Hi,

Not sure if I am doing something wrong, but I get this error on a SSLLabs check;

HTTP Requests: (Request failed)

My Hitch config:
backend = "[127.0.0.1]:8080"
frontend = "[*]:443"
log-level = 1
keepalive = 5
workers = 8
daemon = on
sni-nomatch-abort = on
pem-file = "/etc/apache2/certs/certname/ssl-cert.combined.crt" 
pem-dir = "/etc/letsencrypt/live-pem-files"
pem-dir-glob = "*.pem"
user = "_hitch"
syslog = on
ciphers = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
prefer-server-ciphers = on
alpn-protos = "h2,http/1.1"
tls-protos = TLSv1.0 TLSv1.1 TLSv1.2
write-proxy-v2 = on

On port 443 there is a Nginx proxy to Port 80 (Apache).
In the browser everything is okay, on SSLLabs I get the error above.

**Comment by robinbohnen** [comment]
Found a clue at least; when I disable http2 on the listener of nginx, it stops working.
When I then disable alpn-protos in the hitch config, it starts working again. 

It has something to do with http2, the backend needs to speak it, otherwise it won't work, but the returned information on eldery clients is still http2 (even if they can't understand it).

**Comment by l0stman** [comment]
Hi,

I think nginx just [ignores](https://hg.nginx.org/nginx/rev/416953ef0428) the TLV parameters last time I checked.  So
it doesn't know that the client doesn't support http2.

**Comment by daghf** [comment]
Hi @robinbohnen 

Hitch will transmit the result of the protocol negotiation to its backend as part of the PROXYv2 preamble to allow the backend application to learn which protocol the client is speaking.

It sounds like you need to send traffic to different endpoints based on the result of the protocol negotiation. Since Hitch only supports one single backend, this is not possible.

**Comment by robinbohnen** [comment]
Hi @daghf that is not the case; it has a single backend. See the config at the top.
It is because Hitch and Nginx think everyone supports http2 but elderly clients don't and don't understand the reply in that case.

**Comment by daghf** [comment]
@robinbohnen So there is a mismatch between the ``alpn-protos`` in your configuration (http/1.1, h/2), and what the backend in your case supports (h/2).

As long as Hitch only supports a single backend, and nginx can't be configured to use both h/1.1 and h/2 on the same endpoint, there isn't much we can do here.
