### ISSUE TITLE
hitch.conf missing?

### ISSUE THREAD

**Issue by toby1kenobi** [varnish/hitch#300]
I've tried to apply the [Varnish/Hitch](https://docs.varnish-software.com/tutorials/hitch-letsencrypt/) guide the Ubuntu 18.04. I got to the end and have the various components running, I can't browse the resulting site securely though, no connection can be made. netstat shows nothing listening on 443 - is it naive of me to expect there to be?! 

One thing I noticed was that [step 6](https://docs.varnish-software.com/tutorials/hitch-letsencrypt/#step-6-start-hitch) seems to imply the file `/etc/hitch/hitch.conf` should exist - it doesn't until I create it, and then just contains the line with the reference to the pem file. 

I do see a `/usr/share/doc/hitch/examples/hitch.conf.example`, which does look like it would set Hitch up to listen on port 443 - should I be using something like that?

**Comment by Dridi** [comment]
That looks like a packaging bug, but not a bug from us:

https://packages.ubuntu.com/bionic/amd64/hitch/filelist
https://packages.debian.org/stretch/amd64/hitch/filelist

My hypothesis is that it was missing in Debian first, and Ubuntu inherited the packaging as is.

Summoning @ssm.

For your step 6, you could just proceed and create your own config file.

**Comment by toby1kenobi** [comment]
Ok, thanks - is the example conf file a decent starting point (it looks like it, I'm new to Hitch though)?

**Comment by dmatetelki** [comment]
@toby1kenobi 

The minimal config file is the following 3 lines:
```
# Listening address.
frontend = "[*]:8443"
# Upstream server address
backend = "[127.0.0.1]:8000"
# SSL x509 certificate file.
pem-file = ""
```

The following link helps you how to create the PEM file: https://github.com/varnish/hitch/blob/master/docs/configuration.md
All the config file options are explained in the man page: `man 5 hitch.conf`

**Comment by toby1kenobi** [comment]
Thanks very much, I'll have a go

**Comment by dmatetelki** [comment]
The default.cfg is in the source: https://github.com/varnish/hitch/blob/master/src/tests/configs/default.cfg
