### ISSUE TITLE
Support for Name-based Virtualhost

### ISSUE THREAD

**Issue by tsu1980** [varnish/hitch#302]
I read the doc for [virtual hosts](https://github.com/varnish/hitch/blob/master/docs/vhosts.md) but it seem to cannot configure multiple frontends which have same hostname and port.

I want to scope SSL certificate set per hostname. Can I configure?

Like this
```
frontend = {
    host = "example.com"
    port = "443"
    pem-file = "certs/example.com.pem"
}
frontend = {
    host = "*.example.com"
    port = "443"
    pem-file = "certs/_wildcard.example.com.pem"
}
frontend = {
    host = "www.foo.com"
    port = "443"
    pem-file = "certs/www.foo.com.pem"
}
```

### My situation
To explain my situation, There are multiple hostnames in a hitch instance(Multi-tenant, Multi-Site). And each hostname can bind an SSL certificate.
And my current configuration is this.
```
frontend: "*:443"
pem-file = "certs/example.com.pem"
pem-file = "certs/_wildcard.example.com.pem"
pem-file = "certs/foo.com.pem"
```
If SSL certificate is UCC/SAN(include multiple domains) and `example.com.pem` include "foo.com", it will be conflict(Load wrong hostname's SSL certificate). If Hitch supports virtual host feature. I can scope SSL certificate per hostname explicitly.

**Comment by Dridi** [comment]
There's no virtual hosting in Hitch and even the name popularized by Apache httpd doesn't make much sense.

The host of a frontend is a listening address (either an IP address or a host name to resolve), so you may have multiple frontends if you wish to listen to separate public interfaces for example. If you have multiple certificates for a given domain, you need to fix this by either changing the order of your pem files from most to least specific (typically wildcard goes last) and ideally make sure that a certificate for x doesn't also encompass y and vice versa.

In your example, that would be:

```
pem-file = "certs/foo.com.pem"
pem-file = "certs/example.com.pem"
pem-file = "certs/_wildcard.example.com.pem"
```

Assuming of course that `foo.com.pem` doesn't also include a certificate for `example.com`.

The SNI extension should also help deliver the right certificate for a given host name, but you need to get the order right in the first place.
