### ISSUE TITLE
Hitch with Varnish generates a lot of sc_rx_junk session closes with h2

### ISSUE THREAD

**Issue by Littlericket** [varnish/hitch#314]
We're seeing alot of session error closes on varnish (sc_rx_junk, around 20-50 per second) when using hitch infront of varnish with both proxy enabled. We have no errors when running without hitch (over http). Is this a normal behaviour, because this actually looks wrong to me. Disabling h2 and PROXY also fixes this, so it looks more like a hitch issue to me.

```
frontend = {
    host = "*"
    port = "443"
}
backend = "[127.0.0.1]:6086"
workers = 8
keepalive = 300
pem-dir = "/etc/hitch/certs.d/"
pem-dir-glob = "*.pem"

daemon = on
user = "hitch"
group = "hitch"
alpn-protos = "h2, http/1.1"
write-proxy-v2 = on
syslog = on
log-level = 1
```

**Comment by daghf** [comment]
Hey

This is actually a Varnish issue. It will just close any H/2 sess with an rx junk session close reason, regardless of it being junk or not.

See https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishd/http2/cache_http2_session.c#L437-L438

**Comment by Littlericket** [comment]
So is there a need to open up a Varnish issue or is this getting fixed (theres a TODO) anyways?
