### ISSUE TITLE
Core dump when listening to multiple interfaces

### ISSUE THREAD

**Issue by FathiBenNasr** [varnish/hitch#317]
Hello,

I am trying to get hitch listen on both ipv4 and ipv6 simultaneously. I got it listening on either ipv4 or ipv6, but when i configure it to listen on both like the following:
frontend = {
    host = "*"
    port = "443"
}

frontend = {
    host = "fd22:5979:45f3:9471::1"
    port = "443"
}

I get: /usr/sbin/hitch --pidfile=/run/hitch/hitch.pid --config=/etc/hitch/hitch.conf
Erreur de segmentation (core dumped)

or on the syslog:
 kernel: hitch[1663]: segfault at 0 ip 00007f7b0d40943e sp 00007ffd685b57d8 error 4 in libc-2.28.so[7f7b0d378000+1ba000]
hitch.service: Main process exited, code=dumped, status=11/SEGV
hitch.service: Failed with result 'core-dump'.
systemd-coredump[1666]: Process 1663 (hitch) of user 0 dumped core.#012#012Stack trace of thread 1663:#012#0  0x00007f7b0d40943e __strcmp_sse2 (libc.so.6)#012#1  0x0000559bb0cbcee4 front_arg_add (hitch)#012#2  0x0000559bb0ccf7f2 yyparse (hitch)#012#3  0x0000559bb0cbf7d0 config_parse_cli (hitch)#012#4  0x0000559bb0cb8041 main (hitch)#012#5  0x00007f7b0d39b813 __libc_start_main (libc.so.6)#012#6  0x0000559bb0cba3be _start (hitch)
kernel: hitch[1681]: segfault at 0 ip 00007fd4f1d6443e sp 00007ffd798e9378 error 4 in libc-2.28.so[7fd4f1cd3000+1ba000]
 
System: centos-release-8.0-0.1905.0.9.el8.x86_64 running as KVM virtual machine.
Hitch: hitch-1.5.0-3.el8.x86_64

Is someone able to reproduce this ?

**Comment by dmatetelki** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:32
32      ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:32
#1  0x000055555555ec2c in check_frontend_uniqueness (cur_fa=0x555555787ad0, cur_fa=0x555555787ad0, cfg=0x555555782260) at configuration.c:749
#2  front_arg_add (cfg=cfg@entry=0x555555782260, fa=0x555555787ad0) at configuration.c:790
...
(gdb) f 1
#1  0x000055555555ec2c in check_frontend_uniqueness (cur_fa=0x555555787ad0, cur_fa=0x555555787ad0, cfg=0x555555782260) at configuration.c:749
749                     if ((cur_fa->ip == NULL || strcmp(cur_fa->ip, fa->ip) == 0) &&
(gdb) p fa->ip
$4 = 0x0
```

I'll take a look.
