### ISSUE TITLE
I want to know why do not launch hitch as root permission

### ISSUE THREAD

**Issue by yugun** [varnish/hitch#320]
hello

I'm checking the hitch for the SSL offloading of our project.

I ran a hitch to try demo, but hitch said "Refusing to run workers as root" and cannot execute it.

I have read #168 issue( In fact, that issue is top link when I search Google for that message ),

but there is no reason why I should not execute it as root. ( Just read -u/-g options )

I also read source code "hitch.c" and I found program exited when geteuid == 0 

I'm considering comment that code out,  if the work doesn't have a serious impact on us.

I would be very grateful if you could tell me what the problem is with the root account.

thank you!

**Comment by dmatetelki** [comment]
Hi @yugun,

From the docs: https://github.com/varnish/hitch/blob/master/docs/configuration.md

> Run environment
> ...
> If you are listening to ports under 1024 (443 comes to mind), you need to start Hitch as root. In those cases you must use --user/-u to set a non-privileged user hitch can setuid() to.

I added just this line to the end of `hitch.conf.example`  to test it: 

```
daemon = off
pem-file="./src/tests/certs/default.example.com"
```

Ad it went fine:

```
$ who am i
dmatetelki pts/2        2019-11-14 12:27 (:0)
$ sudo ./src/hitch --config=./hitch.conf.example --user=dmatetelki
20191115T130816.468918 [24300] {core} hitch 1.5.0 starting
20191115T130816.472884 [24300] {core} Loading certificate pem files (1)
20191115T130816.474363 [24301] {core} Process 0 online
20191115T130816.474515 [24302] {core} Process 1 online
20191115T130816.474803 [24303] {core} Process 2 online
20191115T130816.475149 [24300] {core} hitch 1.5.0 initialization complete
20191115T130816.475100 [24304] {core} Process 3 online
```

**Comment by yugun** [comment]
I'm appreciate for your answer. @dmatetelki

In fact, I have launched hitch in two ways.

One way is using --user option ( you told ),

and the other is commenting src code that check geteuid out.
(in spite of  its abnormal way)

In my system, It's uncomfortable to create another account,

so I want to launch hitch with root account.

**Is there a threat or security problem when I run hitch with root account?**

thank you!

**Comment by dmatetelki** [comment]
Apoligies, @yugun, I completely missed your point that you want to run it as root.

You are correct, it is now not possible, due to security concerns. Our big fear is that the user by accident can run hitch as root.

I talked with the lead programmer and we can make it possible, by forcing the user to set root as user AND as user group.

This would be explicit and we could avoid accidents.

It will look like this:
```
sudo ./src/hitch --config=./hitch.conf.example --user=root --group=root
```
Let me implement it quickly.
