### ISSUE TITLE
Certificate load order

### ISSUE THREAD

**Issue by diegosuarez** [varnish/hitch#323]
I've checked documentation and I can't find it anywhere. Which order are loaded the certs? In case of a colision, which takes preference? It would be nice to have it documented. 

We are using some directives `pem-file` followed by a `pem-dir` where a lot of letsencrypt autogenerated certificates are. We had the case of adding a pem-file with a new certificate and we didn't know there was an old, expired cert for the same site (the new one in pem-file directive was a wildcard).
The old and expired certificate was taking precedence in this case. The contrary should be a nice to have functionality, preferring fresh certificate over expired ones, but if it's a difficult task, merely having in the documentation the loading order of the certs should be enought.

Best, 

Diego.

**Comment by diegosuarez** [comment]
Hello, 

Any news on this issue? Can you provide additional info about what order of preference is set?

Best, 

Diego.

**Comment by daghf** [comment]
Hi @diegosuarez 

I just pushed a doc update, https://github.com/varnish/hitch/commit/ce7cb2818c7db23018ed23fb973a9956d9c281b5

I added some notes there on how Hitch deals with name clashes - hopefully that clears things up.

**Comment by diegosuarez** [comment]
Much better :) It's now crystal clear!
