### ISSUE TITLE
Integration with varnish problem

### ISSUE THREAD

**Issue by albert-t25** [varnish/hitch#329]
I'm setting up hitch to serve as proxy to varnish and my hitch config file looks like

```
frontend = "[*]:443"

backend = "[localhost]:8443"

write-proxy-protocol-v2 = on

pem-file = "/etc/letsencrypt/live/example.com/hitch-bundle.pem"

ciphersuites = "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256"

ciphers = "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA38$

tls-protos = TLSv1.2 TLSv1.3

ecdh-curve = "X25519:prime256v1:secp384r1"

prefer-server-ciphers = false
```
On the other hand varnish is listening on port 8443 (started with `-a :8443,PROXY` option). When I try to open the site I get an empty response and in varnish I can see in the logs that it's closing the session from hitch with "junk data" message (`SessClose RX_JUNK`)

Any idea of what might be wrong? Is there a hitch log file to get more details?

Thanks

**Comment by gquintard** [comment]
are you using http2, and if so, have you activated it on the varnish side?
-- 
Guillaume Quintard

**Comment by albert-t25** [comment]
No I'm not using http2. Is that mandatory with proxy protocol?

**Comment by gquintard** [comment]
it's not, but if you client does, varnish will read H2 as H1, and things
just won't work

-- 
Guillaume Quintard

**Comment by albert-t25** [comment]
It seems the issue was that hitch was accepting http/2 from client and trying to speak http/2 to varnish. After I enabled http/2 in varnish, it's working now. Thanks
