### ISSUE TITLE
support for ALPN(NPN) based routing to backends

### ISSUE THREAD

**Issue by difro** [varnish/hitch#33]
https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation

**Comment by lkarsten** [comment]
Hi.

Thanks for the suggestion. Can you explain how you'd expect this to look? How should it work, what routing decisions do you need to do, and how should it look in the hitch configuration?

**Comment by difro** [comment]
Basically supporting different backends for different protocols negotiated at ALPN(NPN) stage.

For example,
```--spdy2-backend```, ```--spdy3-backend```, ```--h2-backend``` options for configuring backends for spdy/2, spdy/3, http/2 protocols, and then we can put different backend servers for decoding different protocols. (eg: nginx for raw spdy protocols, nghttp2 for h2 protocols, etc,...)

Something like what haproxy is doing in this [post](https://www.igvita.com/2012/10/31/simple-spdy-and-npn-negotiation-with-haproxy/)

**Comment by lkarsten** [comment]
Hi. Feature requests are tracked in the wiki. I've added your request there now:
https://github.com/varnish/hitch/wiki/Future-features

Feel free to add to it if you have further details.
