### ISSUE TITLE
Add alpn-protos command line option

### ISSUE THREAD

**Issue by ThijsFeryn** [varnish/hitch#339]
I'd like to have a `--alpn-protos` command line option that allows me to define which *application layer protocols* I want to support.

From a *Docker* point of view, this would be a convenience, and would allow me to tackle the following issue on-the-fly:

```
alpn-protos is specified with more than one protocol while proxy-v2 is  not selected. This is a configuration error.
```

**Comment by daghf** [comment]
Turns out we already have this, it was just missing from the --help output.

Fixed via https://github.com/varnish/hitch/commit/bd7806ec601b15fc846eaf9780945c35816fd625
