### ISSUE TITLE
Add tls-protos command line option

### ISSUE THREAD

**Issue by ThijsFeryn** [varnish/hitch#340]
I'd like to have a --tls-protos command line option that allows me to define which TLS protocols I want to support.

Currently `--tls` only supports `TLSv1`. This `--tls-protos` command line option would allow me to tune TLS protocol informaiton on-the-fly. From a Docker point of view, this would be a convenience.

**Comment by daghf** [comment]
Fixed via https://github.com/varnish/hitch/commit/204c678bb6cfe431f2f057952de708705d01aa97
