### ISSUE TITLE
Backend "intelligence" [non-issue question]

### ISSUE THREAD

**Issue by ioolkos** [varnish/hitch#348]
The documentation reads that Hitch is "designed to be paired with an intelligent backend like Varnish Cache".

But I take Hitch can be paired with any TCP backend, without implementing specific "intelligence". Am I correct about that?

Please forgive this basic user question & thank you for your confirmation.

**Comment by gquintard** [comment]
@ioolkos , smarter is better, but indeed, you can use it with anything that will speak PROXY or even just TCP :-)
