### ISSUE TITLE
hostname resolution

### ISSUE THREAD

**Issue by gquintard** [varnish/hitch#358]
@sudazzle opened https://github.com/varnish/docker-hitch/issues/5 and while there's a work around to fix it at the `docker-compose` level, it could be interesting to have `hitch` be a bit more tolerant about this and notably do an on-the-fly resolution before opening a socket.

I know `varnish` function the same way, but `hitch` doesn't have `vmod_goto` and `vmod_dynamic` to sidestep the issue.

**Comment by daghf** [comment]
We do already have a feature that enables Hitch to periodically refresh the backend IP number. Is this workable as a solution here?

via `hitch.conf(5)`

```
backend-refresh = <number>
--------------------------

Number of seconds between periodic backend IP lookups, 0 to disable.
Default is 0.
```

**Comment by gquintard** [comment]
that's one of those cases where I think doing it in the critical path would make more sense, but the current solution will work. Sorry I missed it
