### ISSUE TITLE
Support changing configuration while running.

### ISSUE THREAD

**Issue by lkarsten** [varnish/hitch#36]
It should be possible to change the list of certificates during normal operations. Normal way of signalling this from outside would be through SIGHUP.

On a SIGHUP with a valid configuration file read, we should signal the children to finish up connections and die, and fork off new ones with the fresh configuration.

This will lead to potentially many extra hitch processes hanging around waiting for slow connections to finish, but this seems preferable to aborting/closing off connections. (either immediately or in n seconds.)

Open question is what to do if we can't bind to new socket given in the new configuration file.

**Comment by perbu** [comment]
The norm is to abort. The socket is quintessential for operation and without there isn't much point in hanging on. It would be beneficial if the init script could be used to do this in a way that could signal back to the user if the reload was successful or not.

**Comment by lkarsten** [comment]
This has arrived in 1.1.0-beta1.
