### ISSUE TITLE
Openssl 3 support planned?

### ISSUE THREAD

**Issue by ehdis** [varnish/hitch#368]
Just wondering if there are any considerations to implement openssl 3 support? Thanks!

**Comment by ehdis** [comment]
Nice to read. BTW, Red Hat and the upstream CentOS  are already on that rail:

https://www.redhat.com/en/blog/whats-new-rhel-90-beta

https://gitlab.com/redhat/centos-stream/rpms/openssl

**Comment by ingvarha** [comment]
And Fedora, of course:
https://src.fedoraproject.org/rpms/openssl

**Comment by iammeken** [comment]
Please ...

Ubuntu 22.04 comes with openssl 3.0.2

**Comment by ingvarha** [comment]
I didn't do anything special to make hitch compile against openssl3. Seems to just work

 [ingvar@nohup ~]$ ldd /usr/sbin/hitch | perl -ne '/ => (\S+) / and print "$1\n";'
 /lib64/libssl.so.3
 /lib64/libcrypto.so.3
 /lib64/libev.so.4
 /lib64/libc.so.6
 /lib64/libz.so.1
 /lib64/libm.so.6

 [ingvar@nohup ~]$ rpm -qf /lib64/libssl.so.3 /lib64/libcrypto.so.3
 openssl-libs-3.0.3-1.fc36.x86_64
 openssl-libs-3.0.3-1.fc36.x86_64

**Comment by daghf** [comment]
This was fixed via 6f5d73d7057dbd5eaa149548688594cd8525fa9d. Closing
