### ISSUE TITLE
1.0.0-beta4 segfaults when enabling syslog

### ISSUE THREAD

**Issue by ingvarha** [varnish/hitch#37]
hitch-1.0.0-beta4 segfaults when enabling syslog. Tested on f22 and el7.

$ hitch-openssl -s /etc/pki/tls/private/default.example.com.pem
20150803T164745.923021 [ 3017] {core} Using OpenSSL version fbad2084.
Segmentation fault (core dumped)

Removing commit 8389be5863318d4859c70854290f02922a1a4082 fixes it.

Note that running without syslog works fine:

$ hitch-openssl /etc/pki/tls/private/default.example.com.pem
20150803T164707.994662 [ 3008] {core} Using OpenSSL version 100010bf.
20150803T164707.995170 [ 3008] {core} Listening on 0.0.0.0:8443
20150803T164707.995260 [ 3008] {core} Listening on [::]:8443
20150803T164707.999503 [ 3008] {core} Using DH parameters from /etc/pki/tls/private/default.example.com.pem
20150803T164708.001633 [ 3008] {core} DH initialized with 1024 bit key
20150803T164708.003292 [ 3008] {core} ECDH Initialized with NIST P-256
20150803T164708.003571 [ 3009] {core} Process 0 online
20150803T164708.003620 [ 3009] {core} Successfully attached to CPU #0
^C
20150803T164709.254673 [ 3008] {core} Received signal 2, shutting down.

**Comment by ingvarha** [comment]
Sorry, commit f7078b62b033e57befefc0ac2097fee61571b175 is the culprit. Removing it makes hitch stop segfaulting again.

**Comment by daghf** [comment]
Hi Ingvar,

turns out this was already resolved in b22d11af4c5c89c2e7ec56bc4f8096d5dd678d8d.

Could I ask you to try current master?

**Comment by ingvarha** [comment]
----- On Aug 4, 2015, at 12:05 PM, Dag Haavi Finstad <notifications@github.com> wrote: 

> Hi Ingvar,

> turns out this was already resolved in b22d11a .

> Could I ask you to try current master?
Current master compiles and starts without errors, including with syslog on my fedora 22. 

Ingvar

**Comment by daghf** [comment]
Thanks!
