### ISSUE TITLE
Github releases not up to date

### ISSUE THREAD

**Issue by Phil-Betts** [varnish/hitch#372]
The latest release is 1.7.2 as listed on hitch-tls.org, but according to github, the latest release is 1.7.0.

## Expected Behavior
The latest release should be available (as a release) on github

## Current Behavior
The latest release according to https://github.com/varnish/hitch/releases is 1.7.0 - which is two releases behind what is shown on https://hitch-tls.org/

## Context
We use a number of open source packages, which we build from source, and which we try to keep up to date, primarily for security reasons.  We have a script which uses curl and the github API to pull in the latest release of each package.  Unfortunately, this does not work for hitch, because github's releases are not kept up to date.

**Comment by daghf** [comment]
Hi

Seems we forgot about the github releases list. I've added the latest on there now.

Thanks for the reminder.
