### ISSUE TITLE
Any plan to support for h3?

### ISSUE THREAD

**Issue by iammeken** [varnish/hitch#375]
nginx just released:
https://www.nginx.com/blog/binary-packages-for-preview-nginx-quic-http3-implementation/

**Comment by daghf** [comment]
Hi @iammeken 

We will not pursue h/3 in Hitch.

Hitch has always been what you can call a "dumb proxy", it is strictly focused on the TLS bits, and never cares about the actual payload. With this scope in mind, it's not a natural candidate for a full-blown QUIC/h3 implementation.

As an aside, there are plans for pursuing h/3 in Varnish Cache but that's still very early days.
