### ISSUE TITLE
tarballs don't include init/service scripts

### ISSUE THREAD

**Issue by jb-wisemo** [varnish/hitch#385]
To start hitch at the correct step of OS boot, init scripts or IBMhat service files are generally needed, but the distributed tarballs (such as hitch-1.8.0.tar.gz) don't include those, even though they are included in prebuilt binary packages.  For now, I am using customized scripts for my systems, but having the upstream scripts as reference would still be useful .

**Comment by gquintard** [comment]
Hi,

Source tarballs generally have no business including init scripts as those depend on the platform the binaries will run on. I think what you want is the packaging [repository](https://github.com/varnish/pkg-hitch) instead.

Kind regards
