### ISSUE TITLE
Protocol of the original https request in forward headers

### ISSUE THREAD

**Issue by ktk** [varnish/hitch#39]
I'm using hitch to terminate a `https` connection which is sent to Varnish and then to the backend. In my use case I do a GET on `https://gont.ch/Municipality`. It seems that the backend does not see that this was coming from `https`. I expected that some header is set, for example `x-forwarded-proto` or the new `Forwarded: proto=https` defined in [RFC7239](https://tools.ietf.org/html/rfc7239). For my use case this is crucial as my middleware needs to know the exact URI from the request, including the protocol.

In tcpdump I see:

```
# tcpdump -i lo -s 0 -A 'tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x47455420'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 65535 bytes
21:52:08.269198 IP localhost.54990 > localhost.9501: Flags [P.], seq 271356757:271357093, ack 670393674, win 342, options [nop,nop,TS val 159634882 ecr 159634882], length 336
E...F.@.@.............%..,.U'.eJ...V.x.....
        ...     ...GET /Municipality HTTP/1.1
Host: gont.ch
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
X-Forwarded-Port: 80
X-Forwarded-For: ::1
X-Varnish: 588473128
Accept-Encoding: gzip
```

But it seems this is already the request Varnish sends to the configured backend.

In Varnish log I see:

```
# varnishncsa                                                                                         
::1 - - [26/Aug/2015:21:59:00 +0200] "GET http://gont.ch/Municipality HTTP/1.1" 404 399 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0"
```

The `404` is what the backend sends because Varnish requested the `http` resource and not the `https` one.

So what I am trying to understand is do I have to change something in hitch/Varnish or do I get something wrong here?

Also where would I have to sniff to see the request between hitch and Varnish?

**Comment by perbu** [comment]
hitch isn't a HTTP proxy, so it can't really add headers. However, in Varnish you should be able to detect that the `client.ip` is that of the loopback (127.0.0.1) which means the request originated locally, telling you that it came over the proxy.

In the upcoming Varnish release (4.1) you can use the proxy protocol which will set the various variables so you'll can do this in a slightly nicer manner.

There might be a patch submitted to the varnish-dev mailing lists that gives varnish proxy support.

**Comment by fgsch** [comment]
FWIW. Here's a working example:

```
import std;

sub vcl_recv {
   if (std.port(local.ip) == 80) {
     return (synth(700));
   }
}

sub vcl_synth {
  if (resp.status == 700) {
    set resp.http.location = "https://" + req.http.host + req.url;
    set resp.status = 302;
    return (deliver);
  }
}
```

**Comment by bnegrao** [comment]
Hi. 

"perbu" said "In the upcoming Varnish release (4.1) you can use the proxy protocol which will set the various variables so you'll can do this in a slightly nicer manner."

Now that Varnish 4.1 is released, how can I solve the issue from this thread? What is the 'nicer manner'?

**Comment by craigcarnell** [comment]
@ktk Any progress on this issue? My PHP application is expecting X-Forwarded-Proto to be set, which is usually added by nginx. But in this case I am doing this:

hitch (443) -> Varnish PROXY -> nginx (8080). My application only knows about 8080.

In PHP this is normally accessible by "$_SERVER['HTTP_X_FORWARDED_PROTO']"

**Comment by Dridi** [comment]
You already have all you need, I'm adding XFP to @fgsch's example:

```
import std;

sub vcl_recv {
   if (std.port(local.ip) == 80) {
     return (synth(700));
   } else {
     set req.http.X-Forwared-Proto = "https";
   }
}

sub vcl_synth {
  if (resp.status == 700) {
    set resp.http.location = "https://" + req.http.host + req.url;
    set resp.status = 302;
    return (deliver);
  }
}
```

**Comment by craigcarnell** [comment]
@Dridi Thank you for the example. I tried this in vcl_recv:

```
if (std.port(local.ip) == 443) {
     set req.http.X-Forwared-Proto = "https";
   }
```

However, in my application the variable was not set. Varnish was restarted following the change to default.vcl

**Comment by craigcarnell** [comment]
@Dridi I changed it to server.ip and that worked for me. On my local machine, hitch, varnish and nginx are running on the same box. 

what is the difference between local.ip and server.ip in this case?

**Comment by Dridi** [comment]
@craigcarnell this is just an example, it all depends on your varnish setup.

See:
https://www.varnish-cache.org/docs/4.1/whats-new/changes.html#proxy-protocol-support
https://www.varnish-cache.org/docs/4.1/whats-new/upgrading.html
