### ISSUE TITLE
Unexpected format for backend argument

### ISSUE THREAD

**Issue by KristianLyng** [varnish/hitch#40]
The -b seems to insist on the ipv6-like square brackets, which makes sense for IPv6, but is uncommon for anything else. The documentation says the format is --backend=[HOST]:port, but this can easily be read as "host is an optional part" (I'm fairly sure there's a remote proxy that'll allow -a :6081 for instance, so this is not completely unreasonable to assume).

I'm not entirely sure why square brackets are required except for IPv6, but at the very least, the documentation should to be clearer on this point.

**Comment by lkarsten** [comment]
This issue doesn't look very actionable, at least without breaking backward compatibility on the configuration format.

@daghf will the 1.2.0 work fix this somehow?

Time this out and move it to future features after April 1st 2016 if nothing has happened by then.

**Comment by daghf** [comment]
I echo @lkarsten's statements above - we can't really change this at this point. Closing this for now.

We could possibly add support for something like the following (for the config file):

<pre>
backend = {
  host = "1.2.3.4"
  port = "80"
}
</pre>
