### ISSUE TITLE
Wish/suggestion: EXAMPLE section in man file to generate snakeoil cert

### ISSUE THREAD

**Issue by KristianLyng** [varnish/hitch#41]
It took me quite a while to figure out the format for the certificate, and as you can see here http://ingvar.blog.redpill-linpro.com/2015/06/26/hitch-1-0-0-beta3-for-fedora-and-epel/ , Ingvar suggests just downloading something he made. This seems to apply to any project involving ssl/tls certificates, but the last step required for the certificates was a bit unexpected to me.

Obviously for production you need a proper certificate and whatnot, but particularly now when Hitch is young, I think it's important to make it easy for people to test.

Suggestion: Move parts of https://github.com/varnish/hitch/blob/master/src/tests/certs/README to a more discoverable place. I suggest an EXAMPLES section in the man file. (Possibly add non-Debian specific variant, until the rest of the world catches up to the brilliance of Debian).

**Comment by lkarsten** [comment]
This is already documented in https://github.com/varnish/hitch/blob/master/docs/certificates.md .

Assuming you've read this, is your suggestion that we put it in the man page?

**Comment by KristianLyng** [comment]
Not necessary, but then the issue is: doc/certificates.md is not distributed in the tar-ball :)

I would still suggest at least something in EXAMPLES or  reference to that file in the man file, if there was a doc/ in the tar-ball, I would've read that of course.
