### ISSUE TITLE
Options missing from man file

### ISSUE THREAD

**Issue by KristianLyng** [varnish/hitch#42]
A large number of options are undocumented in the man file, but documented in --help. Some only have their short option name listed. This is the list I found (might be incomplete):

- [ ] --config (and how to use it)
- [ ] --ciphers (long name)
- [ ] --ssl-engine (long name)
- [ ] -O
- [ ] --client
- [ ] -n
- [ ] -k
- [ ] --chroot (long name)
- [ ] --user (long name)
- [ ] -g
- [ ] --quiet (long name)
- [ ] --syslog (long name)
- [ ] --daemon
- [ ] --write-proxy-v1
- [ ] --write-proxy-v2
- [ ] --proxy-proxy
- [ ] --sni-nomatch--abort
- [ ] -t
- [ ] -p
- [ ] -V
- [ ] -h

(check boxes for your convenience)

**Comment by lkarsten** [comment]
Thanks for reporting this.

Man page should be updated now. (commit: d949327afc36e26d68900474e8c2526b15d9b49e)
