### ISSUE TITLE
"write-ip" option mangling http headers under https

### ISSUE THREAD

**Issue by kevinquinnyo** [varnish/hitch#43]
Hello.  I noticed some unparseable / mangled HTTP Headers when using the `write-ip` option.  I was only using it to see what it did, but noticed any HTTPS requests aren't parsing properly.

I have hitch listening on 443 in front of varnish on 80.  Here's what varnishlog shows:

```
-   HttpGarbage    "%02k%b5%b0%fcGET / HTTP/1.1%0d%0aHost: example.com%0d%0aConnection: keep-alive%0d%0aCache-Control: max-age=0%0d%0aAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8%0d%0aUpgrade-Insecure-Requests: 1%0d%0aUser-Agent: Mozilla/5.0 (X11; Linux x86_64) Ap%00"
```

I noticed that this is obviously hex (an ip address before `GET` and hex codes for CRLF after each header line) so maybe that will help your team narrow down the issue.

I've tried the latest 1.0.1 release, as well as the current master branch.

My certificate (.pem) is self-signed, but it works fine when I use pound instead of hitch as the SSL termination.

The problem goes away if I turn off "write-ip".

Here is my hitch.conf:
```
frontend = "[*]:443"
backend = "[127.0.0.1]:80"

workers = 4
user = "www-data"
group = "www-data"

write-ip = on

pem-file = /var/www/example.com/private/ssl/self/example.pem
```

Anyway, it's not a big deal to me as I was just experimenting with the option and noticed it.

If there's any other information I can provide I would be happy to supply it.

**Comment by daghf** [comment]
Hi

For the write-ip option you need specific support for this in the backend application to strip the IP octet prior to starting HTTP processing.

For Varnish in particular (version 4.1.0 and newer), I recommend enabling 'write-proxy', which enables Hitch to issue the PROXY protocol preamble on all backend connections. Make sure to also enable PROXY in Varnish, see https://www.varnish-cache.org/docs/4.1/whats-new/changes.html#proxy-protocol-support
