### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by ktk** [varnish/hitch#45]
I created a Dockerfile for Hitch so I can use it in our setup. It pulls the 1.0.1 tar and builds the image. It's not perfect yet but it's a start. Before I brush it (aka small it after uninstalling all the build tools), what distro do you guys prefer? I can do it either in Centos or Debian/Ubuntu.

I'm more a BSD guy so I really don't care about which Linux base docker image I use :)

Also if I build that stuff will you take over maintenance and push it to Dockerhub? Because I'm not really too much interested in doing this :)

**Comment by ktk** [comment]
I thought about the approach again. I will most probably do it like this:

- one Docker image for building Hitch, as statically-linked binary
- a minimal image for running it, probably built on busybox or something alike

The first step could be replaced if a statically-linked binary could be made available for the releases via Travis CI. Will do an issue for that for discussion

**Comment by lkarsten** [comment]
Static linking against something as volatile as openssl sounds like a bad idea. What is the problem being solved here?

We don't have any preferences wrt. linux distribution, use what you feel works best for you.

The github wiki is the best place to put a docker file for now.

**Comment by ktk** [comment]
In case of OpenSSL issues the Hick and the complete Docker image would simply be rebuilt, I would be surprised if anyone actually is updating the distro within a Docker image.

I will see how it goes and publish the work, we can still discuss details once I'm there.
