### ISSUE TITLE
Provide a configure option to disable rst2man

### ISSUE THREAD

**Issue by ktk** [varnish/hitch#47]
For building the Docker image `rst2man` either pulls a big list of unnecessary dependencies or it's not available at all (for trimmed-down distros like Alpine Linux for example).

It would be great if there is a configure option to disable it, like ` --without-rst2man`

**Comment by lkarsten** [comment]
Yes, this is a good idea. I'll cook something up.

**Comment by ktk** [comment]
Great tnx. I have a Docker image now, will post that soon on Github

**Comment by daghf** [comment]
I just pushed b615aee which should take care of it. You can now specify --with-rst2man=/bin/true to build without rst2man.

**Comment by ktk** [comment]
Great thanks!

**Comment by ktk** [comment]
I switched to tarball now from git master in my Docker image, it does build but there are issues with this option:

```
 ./install-sh -c -d '/usr/local/share/doc/hitch'
 /usr/bin/install -c -m 644 hitch.conf.ex CHANGES.rst README.md '/usr/local/share/doc/hitch'
/bin/true --halt=2 ./hitch.man.rst hitch.8
 ./install-sh -c -d '/usr/local/share/man/man8'
 /usr/bin/install -c -m 644 ./hitch.8 '/usr/local/share/man/man8'
install: can't stat './hitch.8': No such file or directory
Makefile:383: recipe for target 'install-man8' failed
make[2]: *** [install-man8] Error 1
make[2]: Leaving directory '/tmp/varnish-hitch-bb154c1'
Makefile:755: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/tmp/varnish-hitch-bb154c1'
Makefile:454: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```
Still installs and runs fine though
