### ISSUE TITLE
Docker image available at zazukoians/hitch

### ISSUE THREAD

**Issue by ktk** [varnish/hitch#49]
I created a Docker image of Hitch, it can be found here https://hub.docker.com/r/zazukoians/hitch/

Note that this is built from my own fork of Hitch with my patch included to get it built on Alpine Linux. In case you integrate my pull-request https://github.com/varnish/hitch/pull/46 I will switch to the original `master` and once there is a release which builds on Alpine I will switch to that.

In my opinion it would be best if the Docker image is maintained by Varnish/hitch itself so if you are interested in taking that over I will happily create a pull request for it.

**Comment by ktk** [comment]
With merging patch  #46 my Alpine Docker build works out of the box now, thanks! I updated my [docker image](https://github.com/zazukoians/docker-hitch) to use the offical hitch repo instead of my fork.

Once you do the next release I will switch from git build to tar.gz for building it.

I currently do the build outside the Dockerfile (in `build.sh`) but I could integrate that in the Dockerfile as well if this is preferred.

**Comment by ariya** [comment]
The latest release [hitch-1.1.1.tar.gz](https://hitch-tls.org/source/hitch-1.1.1.tar.gz) already contains the said fix.

**Comment by ktk** [comment]
Yes I switched to tar.gz meanwhile, the image at dockerhub is 1.1.1 too.

**Comment by ariya** [comment]
Any other reason to keep this issue open?

**Comment by ktk** [comment]
I was hoping that the Dockerfile gets picked up by the Varnish/Hitch team. If this is not gonna happen anytime soon we can close it. Might be nice if someone could link to the image somewhere though.

**Comment by ariya** [comment]
@ktk The current practice is not to track it at every upstream project (among others, it adds an additional maintenance burden), but to promote it via Docker Hub. See https://docs.docker.com/docker-hub/official_repos/ for more details.

**Comment by ktk** [comment]
@ariya fine with me, mine is at Dockerhub already. So we can close this
