### ISSUE TITLE
Is it possible to run multiple frontend/backend pairs in the same process?

### ISSUE THREAD

**Issue by inklesspen** [varnish/hitch#54]
I have several sets of frontend/backend port pairs for which I want to run hitch on the same machine (using the same certificate). Can I do this, or do I need to start a process for each one?

**Comment by lkarsten** [comment]
Hi.

Currently Hitch does a single backend connection.

We have on our list some thoughts on changing this in the future. Specifically we most likely will have to support sending HTTP/2 (h2c) to one backend and HTTP/1.1 to another, based on ALPN. 

For now I'm afraid you'll have to run multiple processes. It shouldn't be hard. If you run a recent Linux distribution, the multiple instance support in systemd should fit nicely. (I'd love to link to some docs/tutorial on how this can be done, if you go down that route.)

We don't track feature requests in the bug tracker, so I'll close this issue for now.

**Comment by inklesspen** [comment]
I feel like it ought to be a FAQ entry or something, though... I ended up going the multiple-daemon route, but the fact that hitch supports multiple certificates made me initially think this is possible.

(Also, I ran into some weirdness in systemd around working directories and hitch's configuration reloading; I ended up having to specify absolute paths in several places, which I think shouldn't be necessary. I definitely would like to see more suggested systemd setups; I'd offer to contribute, but I don't think I know enough right now.)

**Comment by gooodmorningopenstack** [comment]
Just to note that I was confused about the backend setting too. We are not used to have many frontend for only one backend.
Though, I'm glad that you have it on the features list :)

Thanks.
