### ISSUE TITLE
external dh-params

### ISSUE THREAD

**Issue by wernermo** [varnish/hitch#61]
It would be nice to be able to use external dh-params like in pound or in nginx. On our systems we rotate the params once in a while for security reasons and it would be very inconvenient to extract and add these every time to every certificate.

in pound this can be configured with
```DHParams "/etc/pki/tls/private/dhparam4096.pem"```

**Comment by lkarsten** [comment]
Hi.

Thanks for making contact. Only actionable issues/bugs are kept here.
Feature requests are tracked in the wiki: https://github.com/varnish/hitch/wiki/Future-features

Please add it there if you think this is something we should do when we have some spare time.

If you feel strongly about this and would like to do the work yourself, feel free to open a pull request or make contact on irc to discuss how to proceed.

**Comment by dvershinin** [comment]
A big +1 on this feature request. There is already ability to specify external key file.

The ability to specify external dh-params file is going to make Certbot generated LetsEncrypt certificates directly usable, without any deployment hooks!
