### ISSUE TITLE
Slow startup with 15.000 certificates

### ISSUE THREAD

**Issue by wido** [varnish/hitch#64]
For testing purposes I tried to start Hitch with 15.000 certificates on my local Intel NUC and it took 10 minutes to start the daemon.

The web page says:

``Safe for large installations: performant up to 15 000 listening sockets and 500 000 certificates.``

It seems to be eating 100% CPU on a single-core for a 10 minutes before starting.

<pre>wido@wido-desktop:~/repos/hitch/src$ time sudo ./hitch -n 4 -u nobody -g nogroup --config=/opt/hitch/hitch.conf

real	9m40.088s
user	9m38.482s
sys	0m0.829s
wido@wido-desktop:~/repos/hitch/src$</pre>

Am I doing something wrong or is it normal that it takes so long to start?

<pre>wido@wido-desktop:~$ cat /opt/hitch/hitch.conf |grep "pem-file"|wc -l
15002
wido@wido-desktop:~$</pre>

<pre>wido@wido-desktop:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
wido@wido-desktop:~$</pre>

<pre>wido@wido-desktop:~$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 69
model name	: Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
stepping	: 1
microcode	: 0x16
cpu MHz		: 779.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips	: 3791.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 69
model name	: Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
stepping	: 1
microcode	: 0x16
cpu MHz		: 779.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips	: 3791.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 69
model name	: Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
stepping	: 1
microcode	: 0x16
cpu MHz		: 779.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips	: 3791.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 69
model name	: Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
stepping	: 1
microcode	: 0x16
cpu MHz		: 1300.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips	: 3791.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

wido@wido-desktop:~$</pre>

**Comment by lkarsten** [comment]
Hi.

Thanks for performing the benchmark. :-)

OpenSSL take a long time to create these contexts. Currently they are being loaded sequentially in the parent process. Back when we tested this, we found significant memory usage and some startup time, but yours seem some orders of magnitude higher.

It would be interesting to hear what the process is up to, if you can run it under perf or something similar.

In normal operations a reload will only load the changed certificates, which should complete in seconds.
There is no interruption to the service while it does this.

**Comment by wido** [comment]
We tested this again, but this time with Ubuntu 15.10 which has a newer OpenSSL version:

<pre>root@VM-9d8e8cfd-e30f-4c40-8c4e-2e098b0f11a5:~# time hitch --daemon --pidfile=/run/hitch.pid --user hitch --group hitch --config=/etc/hitch/hitch.conf

real    0m18.673s
user    0m6.780s
sys    0m2.000s</pre>

So it takes just 18 seconds to start.

Ubuntu 14.04 comes with OpenSSL 1.0.1f and Ubuntu 15.10 with 1.0.2d.

So OpenSSL seems to be to blame here.

Our goal is using about 50k certificates when running in production, so we will benchmark some more.

**Comment by wido** [comment]
We tested some more here and running Hitch inside a Docker container from Ubuntu 15.10

100.000 certificates in total.

<pre>20160216T132932.506532 [    1] {core} hitch 1.1.1 starting
20160216T132932.506656 [    1] {core} Using OpenSSL version 1000204f.
20160216T132932.506867 [    1] {core} Listening on 0.0.0.0:443
20160216T132932.506892 [    1] {core} Listening on [::]:443
20160216T132932.506899 [    1] {core} Loading certificate pem files (100001)
20160216T132932.508821 [    1] {core} Note: no DH parameters found in /etc/hitch/certs/35335.server.pem
20160216T132932.508977 [    1] {core} ECDH Initialized with NIST P-256
20160216T132932.509376 [    1] {core} Note: no DH parameters found in /etc/hitch/certs/84942.server.pem
20160216T132932.509464 [    1] {core} ECDH Initialized with NIST P-256
20160216T132932.509838 [    1] {core} Note: no DH parameters found in /etc/hitch/certs/30538.server.pem</pre>

<pre>20160216T133020.467243 [    1] {core} ECDH Initialized with NIST P-256
20160216T133020.467640 [    1] {core} Note: no DH parameters found in /etc/hitch/certs/98930.server.pem
20160216T133020.467732 [    1] {core} ECDH Initialized with NIST P-256
20160216T133020.468105 [    1] {core} Note: no DH parameters found in /etc/hitch/certs/23856.server.pem
20160216T133020.468192 [    1] {core} ECDH Initialized with NIST P-256
20160216T133020.481516 [    8] {core} Process 0 online
20160216T133020.481630 [    8] {core} Successfully attached to CPU #0
20160216T133020.496415 [    9] {core} Process 1 online</pre>

Start at 13:29:32 and online at 13:30:20. That's 48 seconds startup with 100k certificates.

**Comment by lkarsten** [comment]
Hi. This is great news. The numbers you're seeing now are in the range of what we expected.

Do you have any numbers on memory usage for the process when doing all of these certs at once?

**Comment by lkarsten** [comment]
@wido Could you consider writing this up somewhere, so we can add a link in the wiki? I'm sure this would be helpful information for others considering hitch in similar setups.

**Comment by wido** [comment]
@lkarsten Done! I posted it on my blog: http://blog.widodh.nl/2016/05/hitch-tls-proxy-performance-with-15k-certificates/

**Comment by daghf** [comment]
Very nice, @wido - thanks a lot for looking into this, and thank you very much for the writeup!

I added a link to your post on the wiki, https://github.com/varnish/hitch/wiki
