### ISSUE TITLE
Support for separate key files

### ISSUE THREAD

**Issue by mikl** [varnish/hitch#65]
As far as I can see, Hitch only supports having certificate and private key (and dhparams) all in one file. While there's a nice simplicity to this, all other tools I've worked expects (and in many case, only supports) having the key in a separate file from the cert. 

Especially with new tools like [Let's Encrypt](https://letsencrypt.org), Hitch's unique demand for monolithic files is irksome, as you need to regenerate the cert every four months (which is relatively painless, if you're using their scripts, since they provide symlinks to the current cert + key that are automatically updated when the cert is regenerated). It would be great if Hitch could support a similar setup to other software using TLS.

**Comment by lkarsten** [comment]
Hi.

This is currently being developed and will be part of the next release.

In the mean time, you can use a Let's Encrypt client that has support for Hitch: https://github.com/hlandau/acme#comparison-list-of-client-implementations

Closing this as we don't keep feature requests in the bug tracker.

**Comment by lkarsten** [comment]
We forgot about this for 1.2.0. Reopening so we can have another look at it.

**Comment by michaelkennedy** [comment]
Looks like this has not been resolved yet. (as of 1.4.6-1)

Is it likely to make it into any future release?

**Comment by denisbr** [comment]
@michaelkennedy This feature request is being evaluated, in the mean time you could always have a look at this tutorial for how to use Certbot with Hitch through update hooks:
https://docs.varnish-software.com/tutorials/hitch-letsencrypt/
