### ISSUE TITLE
Create a macro table for the configuration file

### ISSUE THREAD

**Issue by Dridi** [varnish/hitch#71]
From the current:

```
#define CFG_CIPHERS "ciphers"
#define CFG_SSL_ENGINE "ssl-engine"
#define CFG_PREFER_SERVER_CIPHERS "prefer-server-ciphers"
#define CFG_BACKEND "backend"
...
```

We could instead do something like:

```
CFG(CIPHERS, "ciphers")
CFG(SSL_ENGINE, "ssl-engine")
CFG(PREFER_SERVER_CIPHERS, "prefer-server-ciphers")
CFG(BACKEND, "backend")
...
```

We could then reuse the table in `configuration.c` as it is currently used and also to generate documentation (I have `hitch(5)` in mind). Of course the table could also include a long description and maybe more.

Thoughts?

**Comment by istolga** [comment]
+1

**Comment by Dridi** [comment]
I had a look at this a while ago, I believe it can be done (and bring benefits) but it currently requires too many changes for my tastes to happen. I'm stepping down on this one, keeping it in mind for maybe later.
