### ISSUE TITLE
libev not found in FreeBSD 10.2

### ISSUE THREAD

**Issue by fgsch** [varnish/hitch#74]
configure.ac should use PKG_CHECK_MODULES when possible and not AC_CHECK_LIB.
AC_CHECK_LIB relies on the linker library search path. In systems where libev is installed in a non-standard path (or when the path is not in the linker's default path) compilation will fail.

```
configure:4391: checking for ev_default_loop in -lev
configure:4416: cc -o conftest -g -O2   conftest.c -lev   >&5
/usr/bin/ld: cannot find -lev
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

The same applies to the ssl check.

**Comment by fgsch** [comment]
Complete output at:

https://jenkins.varnish-software.com/job/hitch-master-gitbuild-freebsd10-amd64/34647/console

**Comment by daghf** [comment]
Thanks.

I briefly looked into PKG_CHECK_MODULES, but it turns out libev in particular doesn't ship with a pkg-config metadata (.pc) file.

Any other clever way to solve this when there's no .pc file?

**Comment by fgsch** [comment]
Both FreeBSD and CentOS have a .pc file for libev.

Maybe we can have both checks?

**Comment by fgsch** [comment]
Any other thoughts on this? 

I can submit a PR to check both.

**Comment by daghf** [comment]
So we make the PKG_CHECK_MODULES check conditional on the existence of a .pc file, and otherwise fall back to AC_CHECK_LIB? Seems like a fine approach to me.

A PR would be very welcome :-)

**Comment by fgsch** [comment]
I had a quick look and it looks like this are pc files rolled by downstream, not part of libev.

Regardless, I will do the changes, test it and submit a PR.
