### ISSUE TITLE
Tests depend bash at some specific path

### ISSUE THREAD

**Issue by fgsch** [varnish/hitch#79]
In systems where bash is in other places (e.g. FreeBSD) tests break:

```
./runtests 
./runtests: Command not found.
```

It'd be great to remove the bash dependency as well.

**Comment by Dridi** [comment]
The workaround is to run `bash ./runtests`, assuming it's in your `$PATH`. I also plan to cut the bash requirement for #73 and in current master you don't need to run the test suite from `src/tests`.

**Comment by fgsch** [comment]
Addressed by PR #81

**Comment by daghf** [comment]
Fixed after merging #81
