### ISSUE TITLE
Why is DHE suites not supported

### ISSUE THREAD

**Issue by HLeithner** [varnish/hitch#83]
I use the following ciphers for hitch

tls = on
ciphers = "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES25
6-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-CAMELLIA128-SHA:DHE-RSA-CAMELLIA256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA:AES256-SHA:CAMELLIA1
28-SHA:CAMELLIA256-SHA:ECDHE-RSA-DES-CBC3-SHA:DES-CBC3-SHA:!LOW:!MEDIUM"
prefer-server-ciphers = on

These ciphers should allow to fall back to a DHE cipher with Forward Secrecy but hitch seams to fail at this point.

Thats the ssllabs output for this config: https://www.ssllabs.com/ssltest/analyze.html?d=itronic.at

**Comment by HLeithner** [comment]
btw. I use Debian Jessie with Openssl 1.0.2g-1

**Comment by lkarsten** [comment]
Hi. Thanks for reporting this. We'll have a look.

**Comment by daghf** [comment]
Hi @HLeithner 

I gave this a try, and the `DHE-` ciphers seem to work correctly as long as you have DH parameters included in your PEM file.

Take a look at https://github.com/varnish/hitch/blob/master/docs/configuration.md#preparing-pem-files and please report back.

Thanks,
Dag

**Comment by HLeithner** [comment]
That was my fault sorry.
