### ISSUE TITLE
global backaddr is assumed to be static

### ISSUE THREAD

**Issue by yogo1212** [varnish/hitch#84]
hi :-)

when configuring a hostname for a backend the hostname is only resolved once in `init_globals`.
=>
in a way, hitch acts as a DNS cache that doesn't respect TTL.

related use case: using amazon ELB as backend.

possible solution: register an event to refresh the cached value of `backaddr` when the DNS value expires.

**Comment by olivierHa** [comment]
Any updates about this issue ? Is this also affecting docker internal name resolution ?

**Comment by yogo1212** [comment]
@olivierHa 
the issue i've described only affects hitch internally.
e.g.
```
start hitch -> A record with TTL 20 received
one minute passes
DNS changes, server goes down
hitch loses connection
hitch retries using the expired address until something stops it.
```

we've replaced hitch with nginx in our application

**Comment by dmatetelki** [comment]
I've started to work on a periodic backend IP check fix (with the guidance of @daghf ), let me update the progress here.

**Comment by rtkbkish** [comment]
@dmatetelki Thanks. This will be very helpful.

**Comment by gquintard** [comment]
I'm interested by the approach here. First thing is when do we update the pool, and the second one is: how do we spread connections? Last one is what do we do in case of failure?

**Comment by dmatetelki** [comment]
Hi @rtkbkish, @gquintard, @yogo1212  and @daghf !

The first version is ready to be tested. (thou i did create a testcase)
The patch:

- introduces a new parameter,  `-R  --backendrefresh=USECS` which allows periodic backend address lookup. You turn it off / have static backend address with value 0. Default is 1s.
- The main process refreshes (or not) the address, and notify the client processes.
- The client processes do the create socket and connect now in `end_handshake`, not in 2 functions, for concurrency safety.
