### ISSUE TITLE
Doesn't restart after yum update

### ISSUE THREAD

**Issue by clarinetlord** [varnish/hitch#88]
Our server did an automatic `yum update` from cpanel and updated hitch to the most recent version. However, in doing so it shut hitch down instead of restarting it, and our site was down until I figured it out and started it again. Here's the message log:

```
May 14 07:22:37 vps18873 pure-ftpd: (?@127.0.0.1) [INFO] New connection from 127.0.0.1
May 14 07:22:37 vps18873 pure-ftpd: (?@127.0.0.1) [INFO] __cpanel__service__auth__ftpd__9drpozwdzjKswIdzvSz6oRGbZgNA1j1Song2srR9b4cSkRhldEdIx5MjT4b9iHUX is now logged in
May 14 07:22:37 vps18873 pure-ftpd: (__cpanel__service__auth__ftpd__9drpozwdzjKswIdzvSz6oRGbZgNA1j1Song2srR9b4cSkRhldEdIx5MjT4b9iHUX@127.0.0.1) [INFO] Logout.
May 14 07:23:11 vps18873 yum[30935]: Updated: hitch-1.2.0-1.el6.x86_64
May 14 07:23:11 vps18873 hitch[26778]: {core} Received signal 15, shutting down.
```

Is this a hitch configuration issue that caused it to shutdown rather than be restarted, or does something need to be fixed elsewhere?

**Comment by Dridi** [comment]
It looks like a packaging issue, where did you get the packages from? EPEL?

**Comment by clarinetlord** [comment]
I believe so. Here's what `repoquery -i hitch` says:

```
Name        : hitch
Version     : 1.2.0
Release     : 1.el6
Architecture: x86_64
Size        : 155539
Packager    : Fedora Project
Group       : System Environment/Daemons
URL         : https://hitch-tls.org/
Repository  : epel
Summary     : Network proxy that terminates TLS/SSL connections
Source      : hitch-1.2.0-1.el6.src.rpm
Description :
hitch is a network proxy that terminates TLS/SSL connections and forwards the
unencrypted traffic to some backend. It is designed to handle 10s of thousands
of connections efficiently on multicore machines.
```

**Comment by Dridi** [comment]
You should file a bug on the Fedora bug tracker for packaging issues. Let's try to solve it here, summoning @ingvarha.

**Comment by ingvarha** [comment]
@clarinetlord, thanks for reporting this. 

Fixed in downstream fedora commit cee4246, http://pkgs.fedoraproject.org/cgit/rpms/hitch.git/commit/?id=cee4246

Updated packages will appear in epel6 eventually.

Ingvar

**Comment by ingvarha** [comment]
@clarinetlord, if you want to test packages before they appear in epel6 updates, please try the builds here: https://bodhi.fedoraproject.org/updates/hitch-1.2.0-2.el6

Adding "karma" points makes it possible to push earlier to epel stable.

Ingvar

**Comment by daghf** [comment]
Looks like this has been fixed downstream - closing.
