### ISSUE TITLE
Don't log children reload as error

### ISSUE THREAD

**Issue by dugwood** [varnish/hitch#98]
When running the `reload` command (`service hitch reload`), hitch returns an error in the log when the old child exits. At first I thought it was bad, but it's not:
![image](https://cloud.githubusercontent.com/assets/5517743/15743151/b2e9e5f4-28c3-11e6-9616-f6153383ee66.png)

Can you use another log level for this action? The error is sent on this line:
https://github.com/varnish/hitch/blob/master/src/hitch.c#L2871

Thanks a lot for this great piece of software.

**Comment by daghf** [comment]
Hey

Thanks for the input - I very much agree.

Will push a fix for this momentarily.

**Comment by dugwood** [comment]
Thanks a lot!
